### ISSUE TITLE
Crash on loading Server Browser

### ISSUE THREAD

**Issue by DiogenesOfMiami** [FakeFishGames/Barotrauma#11551]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I played yesterday without issue, but today, it crashes 3/3 times I launch the server browser.

### Reproduction steps

1. Start the game
2. Skip or wait through opening credits
3. Left-click Server Browser
4. Crash (before or during the part where the servers populate the list)

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/15/2023 17:44:51)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

95F201D2EFA7434B617AF044373BE33E

Game version 1.0.7.0 (ReleaseLinux, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Unix 5.15.0.67 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: An item with the same key has already been added. Key: Manual (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Steamworks.SourceServerQuery.<>c__DisplayClass2_0.<GetRules>g__onRulesResponded|0(String key, String value) in <DEV>\Libraries\Facepunch.Steamworks\Utility\SourceServerQuery.cs:line 28

Last debug messages:
[03/15/2023 17:34:01] Attempting to open ALC device "USB Audio Analog Stereo"
[03/15/2023 17:34:00] Logged in as DiogenesOfMiami.ttv (SteamID STEAM_1:0:123431)


- Crash #2 --------------------------------------------------------------------------------------



Barotrauma Client crash report (generated on 03/15/2023 17:45:56)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

95F201D2EFA7434B617AF044373BE33E

Game version 1.0.7.0 (ReleaseLinux, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Unix 5.15.0.67 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: An item with the same key has already been added. Key: Manual (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Steamworks.SourceServerQuery.<>c__DisplayClass2_0.<GetRules>g__onRulesResponded|0(String key, String value) in <DEV>\Libraries\Facepunch.Steamworks\Utility\SourceServerQuery.cs:line 28
   at Steamworks.SteamMatchmakingRulesResponse.InternalOnRulesResponded(IntPtr thisptr, IntPtr pchRule, IntPtr pchValue) in <DEV>\Libraries\Facepunch.Steamworks\Steamworks.NET\SteamMatchmakingResponses.cs:line 138

Last debug messages:
[03/15/2023 17:45:13] Attempting to open ALC device "USB Audio Analog Stereo"
[03/15/2023 17:45:11] Logged in as DiogenesOfMiami.ttv (SteamID STEAM_1:0:123431)


- Crash #3 --------------------------------------------------------------------------------------



Barotrauma Client crash report (generated on 03/15/2023 17:47:56)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

95F201D2EFA7434B617AF044373BE33E

Game version 1.0.7.0 (ReleaseLinux, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized

System info:
    Operating system: Unix 5.15.0.67 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: An item with the same key has already been added. Key: Manual (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Steamworks.SourceServerQuery.<>c__DisplayClass2_0.<GetRules>g__onRulesResponded|0(String key, String value) in <DEV>\Libraries\Facepunch.Steamworks\Utility\SourceServerQuery.cs:line 28

Last debug messages:
[03/15/2023 17:46:08] Attempting to open ALC device "USB Audio Analog Stereo"
[03/15/2023 17:46:07] Logged in as DiogenesOfMiami.ttv (SteamID STEAM_1:0:123431)
```

**Comment by Calcolan-Was-Somehow-Taken** [comment]
I'm also getting this issue however my last debug message is 

Attempting to open ALC device "Starship/Matisse HD Audio Controller Analogue Stereo"

Also on linux, ubuntu specifically. Until a fix is made I tried just now setting it to force compatibility tools which im assuming made it the windows version and setting the proton version to 8.0 fixed it and let me join a server (Experimental didn't let the game launch). I hope this works for you, please let me know if it does!

**Comment by Regalis11** [comment]
Even though we have been unable to reproduce the issue, we added a fix to this last March (commit in our private repo: https://github.com/FakeFishGames/Barotrauma-development/commit/78d415ea259245175cd8220948374d7e2076f8a0) and haven't gotten any reports about it since, so I think it seems likely it no longer occurs.
