### ISSUE TITLE
Crash because a mod required by some other mod isn't installed

### ISSUE THREAD

**Issue by IfromTurkey55** [FakeFishGames/Barotrauma#11956]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

ı was playin for 3 min
that bum!
its crahes :(

### Reproduction steps

[crashreport (32).log](https://github.com/Regalis11/Barotrauma/files/11405245/crashreport.32.log)

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Vanilla, (Legacy) EK | Armory, Nanobot Dispenser Extended (Equipable healing Item), Barotraumatic New Creatures, Better Pay (More Marks), Barotraumatic Undersea Horrors Fixes, Barotraumatic Xanmonsters1 Fixes, Modular Backpack, AUG Tool revamp, Makeshift Flamer, Barotraumatic Xanmonsters2 Fixes, Deep Sea Alcohol, Europa Fishies, Frith's Biomes, Fabricator6slot, Lightsabers  星战光剑们, More Artifacts 中文补丁, Plants Plus, Russian Navy Equipments, Abyssal Warsuit, [EMS] Prometheus Station, Artifacts Restored, Barotraumatic Monster Pack Test fixes, Barotraumatic Extended Monsters Fixes, BaroTraumatic Nightmare, SaveMyStuff, No Reaper's Tax, useless 2.37, Super Hmg + Exosuit, Let Me Choose !, Better XP Talents, All The Talent Trees + Unlock Parallel Talents, (Legacy) EK | Utility, Storage Icons, Better Dive Suits, PN-21 Colossus Mobile Station, (Legacy) EK | Gunnery, ADV Beacon Stations, Lua For Barotrauma, Ultima Mortis (Warhammer 40k), Sweet Pea, Ulysses 2.37, [VH] The Iroh, LONGBOW sub carrier, Sort Container UI, Europa Express, Crab 1.2, CBS-74 Ptolemaios II, JS Ragna MKIV, Trust full joe, Bob Semple Submersible Tank, 自用Dugong改, Tubarão, OX-17 v0.1, "Hopeye" Class Abyssal Biome Science Submarine, OX-17 v0.2 EK, The Donut, Cardeal, Mercury, Trieste, 7th Fleet Felinis - Volitile, LEGIONAR, Converted Armed Heavy Freighter “Casablanca”, IMC AEGIS, Barsupreme, Hurricane, Sunset SC-I, [Pableqx] Dreadnought BR-3507 - EN/US & PT/BR, 拓冰者级多用途潜艇 Glacier pathfinder class submarine, Kastrull 简单修改版, 【TSM】Snoata '关外', Panzer-Ⅳ 四号坦克, sokayım ışığına, T.I.T.A.N. Warsuit 3.0: Abyss Watcher, Weeb guitar, More Unique Weapons (v1.1) [EN/RU], NI | WEAPONARY 北方工业联合体*的武器拓展俱乐部, SCP Art, Scp Siren, Scp-049 Mod, Unlock Parallel Talents (Updated for 1.0), All The Talent Trees, 天赋点经验(Talent Point EXP), UwU — Restored Talent Items, TaF - EK Pirates, MannaBuildables - EK | Gunnery - Loaders Patch, BaroCraftables, Heavy Crate From Backpacks, Duffle Bag 2.0, Backpack & WaistBelt, EEBD Emergency Escape Breathing Device, Genes+ Revived and Expanded, Playable Mudraptor (Magenta Mix), MoreHeadgear, Better Human Damage, Portable Storage, Objectively the worst orca variant [T3], Beacons Extended, SOFA'S WRECKS, Fallout Power Armor, AUG Guns [Outdated], GunLights Remade [deprecated], Reworked Chaingun, 32x Stack, Balanced Stack 32x Lua, Lua Linker, Codename HONK, Cs For Barotrauma, BetterFabricatorUI, Raptorial -X- 01 - Made for Mudraptors!, Toolbox Expanded, Unlimited Items, The Sculpture, Meaningful Upgrades, Ammo extended 2 (RUS/ENG/汉语), Highly Advanced Gene Splicer, Weapons+, Melee Weapons Pack, Akstely, Wreck Locator, Pelican Cases, Janitor (W.I.P), Mark Currency Mod, Instrumental Music Mod, Super Mining Sonar [UNMAINTAINED], Hydrothermal Synthesis (grow rocks), Visual Variety Pack, New Wrecks For Barotrauma (With sellable wrecks), Unlimited O2 Bottles (Oct 2021) ABANDONED, XanRobots, Hungry Sailor (OUTDATED - CHECK DESC), More Alarm Sounds, Drunken Sailor (OUTDATED - CHECK DESC), Cat, WITHERING SOULS VIII (Functional Necrosis), Meaningful CPR, The Old Man, The Zoo Zipper, Furniture (Barokkea), [CN/EN]Peko items [Urban Expanses Update], Meaningful Drunkenness ? ? ?, Abyssal armory - Reinforcements, No Role Balance, Buy and Craft Electrics (discontinued), Craftable Ammo Updated, Saber Personal Protection (OLD - v0.13.0.11), Defibrillator (Batteries), Apo-4A "Saber", [Obsolete] Community Conversation Pack, Pet Mudraptor -  Holiday Update Hotfix, Zubtrauma (Dialog Only), Astra's Bot Conversation-Dialogue Mod, Medical Headset, [AH]Keypad, SOFA'S DECO, SOFA'S HUMANS, DynamicEuropa, Predators (Yautja), The Thingy!, Pirate Vessels Expanded - Custom Submarines, Telecommunications Mod, RIBA Portable Items - "Ona-Utonula" Update, Skill Magazines - Expert Approved Series, Bodypillows for Barotrauma, Alarms Extended, LetThemIn, Ban hammer, Stations from beyond, Squidd's Expansion🐙, CrouchHarder [Discontinued], NOATUN, Fortunate Worm, Wreck Corpses, Modular Headset - The only headset you'll ever need!, Drainable Headsets, Demonic Creatures, Suicide belt, No Role Balance for Enhanced Armaments, Shinkai Musume, Snoring Moloch, Creatures+, Quieter Sonar Beacon, Electric Guitar, Mercenary Job, Improved HandCannon, ECSS-Harrow (Combat Deep Diver), СБЭУ, NPC Suit, [DS] Skilled Crew, Magical Spells, T.S.M MISSIONS-问君此去几时还, CC's UAPM [deadNgore], Enhanced Armaments 中文补丁, Epic accordion, Acolyte Husk Increased Pressure Resistance, The Sword Core is ready.Keep your enemy close! Titanfall 2 Ronin Swords, Husk Auto-Control [IMPROVED HUSKS], EK | Hardsuits Rebalance, Headsight, Safe Metal Crate, Thalassophobia Jobs | Awesome Compatability Patch, Husk Mod Missions, ZDoors, UwU — PUCS old protection, UwU — Duffelbags, Harmonica Free Bird solo, Decon pls, Deep Sea Creature, Neco-Arc Sonar Replacement, Dynamic Europa RU, JC-07 Scylla ft. Emma the Ship AI, 40k Dark Mechanicus + Loyal Skitari, DynamicEuropa - Default Level Size Patch, Dead Space Uniforms (IN PROGRESS), Improved Husks Fix (OBSOLETE), Chainsaw Death Bringer, MannaBuildables, useless 4.37, Sounds Of Europa, Perlu Pacar Talent Mod, Perlu Pacar Ship Upgrade, Perlu Pacar DE Map Size, Diving masks with Hats, Quality Ammo Boxes, M10 SubPod, EuropaWaifu++ Enhanced Armaments Patch, Real Sonar LITE, Athena, M10 All-In-Pack, Thalassophobia: Remastered, ALIEN - XENOMORPH, Dead Space, Explorer, Breakable Handcuffs, [FIXED FOR 1.0] Mantis Mod, Shipwrecks Extended, A Way Out (WIP), (Legacy) EK | Dockyard, [RH] Tynler, Backpack, Portable Torpedoes, [PESD] Timid Station, SOMA Monsters, EK Tazer Fix, Among Us Accordion, [AH] Lockpick, SOFA'S RANDOM BIOMES, SOFA'S TOOLS, Pockets For All, Chess Set, [AGC] SCP, APFSDS Railgun shells, Nanite Integration, BioTrauma (Bioshock mod), Half-Life Combine Module Pack, oClockRadar / Sonar [Alt Appearance], Lootbelt, Improved XP Rates, Duffelbag Fix / 遺物袋補丁, EuropaWaifu++ Improved Husks Patch, EuropaWaifu++ EK mods Patch, Disconnect Kill And Stun Remover, RIBA Sticky Notes, Stack Size Increase, Apo-5 "Chainsaw", Breaking Bad Guitar, SOFA'S CLOTHES, DRGBeers, Better Vanilla Turret Ammo, 32x Stack - Lite, Performance Fix, Unlimited Railgun EK Armory Pack, Unlimited Gun Ammunition, BaroDrama V4.1, AnimEuropa, KA-BOOM, Talent Gear Found In Wrecks, More XP, Týr-提尔号[cn][en], Submarine Weapon Sound Makeover, Simple Crucifix, Diving Suits Indoors, Smart Auto Door, Life Of A Sailor [Garden Under Maintenance], Lasguns Warhammer 40K, Dont Open Debug Console On Errors, Coulrotrauma, 原版武器重做, Sellable Pirates, EK Mods Русский перевод, [AA] Aquatic Arsenal - Lead Diver Job (WIP), Harlech, Caramellatching, Monster Hunter Barotruma, Suicide Revolver - Револьвер самоубийц - 自杀式左轮枪 - The Easy Way Out, Patcher-9000, Material IO, Fart Honk, Basilisk Battlecruiser, Copperhead, CatMlep Sonar, Universal Turrets 通用炮塔, (DISCONTINUED) Improved Husks (Huskmod) Merchant Patch, Recovering PTSD Headsets, Balloons Mod, Bury The Light Worm, CM-DS, Kasserine, UwU — Crates return steel, UwU — Waterprankster Pressure Immunity, UwU — Upgrade Everything, EuropaWar_Vanilla, One-handed police shield (Одноручный Полицеский щит), old talents+new talents merged talent trees (V1.0), SFB with DE, Unlimited EK Armory, Unlimited EK Utility, CC's UAPM [building], EuropaWaifu++ BaroDrama Patch, SCP 271, Craftable Ammunition Shelf, The Nibbler, CV13——失乐园, IMC SLEDGE, Metro Last Light Guitar, Husk Church Cathedral Visual Pack, [SuS] Traitor gamemode submarine pack!, Ju87 G-1, VulpesZerda, Unlocked talent trees, USS William D. Porter, Norppa, Better Exosuit with Platform 外骨骼优化和置物架, He's a Pirate Accordion, Reworked Talent Trees, Blade Runner Blasters, Mission Count, DynamicEuropa - Default Level Size Patch + Frith's Biomes, [JP] PVP ships pack [PVP], M10prepatch+europawaifu++, The Brizo, ArtifactsBack, Herse AT-III, Analyze Items, 南十字座 CRUX 战列巡洋舰, 军团(Legion)战列舰, GAYGAY Submarine MK6, [Pulsar]U-017, 超时空要塞 VF25 弥赛亚, “暮雨”(沉船）, Project Death Eye | RUS | WIP, The Funhouse, Perlu Pacar Bag Upgrades, 儒艮IV, Cyclopes-01, Narwhal, dolphin, Super Mining Sonar + oClockRadar [UPDATED], S-191 Barracuda (Barsuk Refit), The Coffin, TR-44 "Blimp", M10 All-In-Pack + EuropaWaifu++ Patch, 天佑改 银河号  驱逐舰, Stronger Bandits/Pirates NPC(updated), NEEDS - EuropaWaifu++ Compatibility, Taser Pack, Shreksophone, Unlimited Railgun, [RA] Roskosmos Arsenal [RU/ENG], Unlimited Ammunition Box, Unlimited Tool, Unlimited Railgun EK Gunnery Pack, [Music mod] RIMM Reworked, Larger Deconstructor, Start with More Crew, 拼装模组, Enhanced Armaments, Movable and Sellable Wrecks, More Artifacts (AOCS), Coloured PUCS, Social Husks, ExtraStorage, Walts Handcuffs, MoreMissionsMod, Combinable Ammo Revived (NOW WORKS WITH ALL AMMO), Talent Enhancement[CN/EN/RU/FRN], Bad to the Bone Sonar, Let Them All In, ANGRIER DOOMWORM, BetterHealthUI, 【T.S.M】山河无恙 日月重光, OldItemSpawnsMod, UwU — Basic, Ruins Enhanced, Extract It!, SOFA'S CREATURES, Enhanced Armaments - Legacy Archive, Increased Missions + More Variety (Custom Missions TBD), No Role Balance v2, Indigo project b.1.1 正式版, ek utility+nt cybernetic bent metal patch, Cheeki Breeki Accordion, Old Crew Outfits, Greatly Improved PUCS, STALKER Guitar and Loner Suit, Midround Latejoin Respawner, STALKER Guitar and Harmonica Music, Saber Armaments Revived, Blade Job, ECS SSN - 86 Block I, Maddened Black Sea Armory, Exoskeleton Equipment [Revived], Beaumaris, EuropaWar, ExoSuit & Safety Harness rework, Acolyte Improved Husks Patch, UwU — Medical, Accordion Free Bird solo, Modding Toolkit, Unlimited EK Gunnery, MUX9（暮春之雪）水下旅馆潜艇, DynamicEuropa - Frith's Biomes Compatibility Patch, Silver vulpes, Pillbug, More To Escort x50, Physeter macrocephalus Black, 雾凇 重型科研船, Rustbucket, Stack Size 62x Lua, Icereaper- Mk1, 零镇静, Pockets Superiority, Better Call Saul Guitar, Armory Weapons (and some clown craftables), Husk Mod Missions RU, Ultima Mortis Maximus (Warhammer 40k), Exosuit Retexture, [BOS]Backpack, Minigun, Legacy Music, Auto Reload Lua, Bots operate fabricators, Too Many Missions, Wanted Alive, Hotbar Holdable Guns, Junk & Stuff [ENG/RU], Multiplayer crew manager, Vanilla Weapons Overhaul, More Level Content - 1.0 Update, Fix Improved Husks Waterbreathing, Defender Mod (Job/Pet/Weapons/Items), Creatures of the Depth, Surprise Terrorism, MoreSpawnItems, NEEDS, Quiet Deconstructor &12 slots, 原力武士职业  Force Warrior Job 【WIP】, Enhanced Armaments Barotraumatic Patch, Unoculus (A talking sub), Robo-Trauma, Super Gene Splicer, Simple Gene Rebalance (With Transformations), Parallel Talents Plus, Use Environ Air, Quality Ammo Boxes+ (LUA), Admiral Job (指挥官), Combinable Ammo + Quality Ammo Boxes, BIG Crate, Cat Propaganda Banner Override, The Great Talent Merger of 1.0
Level seed: Kogavostok55
Loaded submarine: Athena Class C MK I (DCA60F57B8C3FD903AC59993B1C773E0)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GT 635
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: "NEEDS" depends on a package with name or ID "Hungry Europans" that is not currently installed. (Barotrauma.MissingContentPackageException)
Target site: System.String get_Value()
Stack trace: 
   at Barotrauma.ContentPath.get_Value() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPath.cs:line 59
   at Barotrauma.Sprite.EnsureLazyLoaded(Boolean isAsync) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sprite/Sprite.cs:line 100
   at Barotrauma.GUIImage.Draw(SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIImage.cs:line 213
   at Barotrauma.GUIComponent.DrawManually(SpriteBatch spriteBatch, Boolean alsoChildren, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 582
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 589
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 589
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 589
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 589
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIListBox.cs:line 1291
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 273
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 160
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 996
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58

Last debug messages:
[05/05/2023 13:05:23] Norman Berlin
[05/05/2023 13:04:53] Cinda Burke
[05/05/2023 13:03:40] Dimitry Cobble
[05/05/2023 13:03:39] Cuck Basnett
[05/05/2023 13:02:55] Peggie Marquez
[05/05/2023 13:02:52] Harry Meza
[05/05/2023 13:02:25] Bettyann Heuer
[05/05/2023 13:02:24] Alonso Heuer
[05/05/2023 13:02:08] Marco Reeves
[05/05/2023 13:01:47] Coleman Banks
[05/05/2023 13:01:05] Jodee Colpitts
[05/05/2023 12:59:08] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/miss_/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Items/arttoolthbelt.png, size: 112x54)
[05/05/2023 12:59:07] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/05/2023 12:59:07] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/miss_/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2931133108/VanillaWeapons/SMG.png, size: 208x119)
[05/05/2023 12:59:07] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/05/2023 12:59:07] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[05/05/2023 12:58:31] WARNING: Potentially invalid damage modifier in ", Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[05/05/2023 12:58:31] WARNING: Potentially invalid damage modifier in ", Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[05/05/2023 12:58:31] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/miss_/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2914415949/Items/Cultist robe.png, size: 569x300)
[05/05/2023 12:58:30] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/miss_/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776026770/Jobgear/noseless_clown/blue_clown_sprite.png, size: 117x55)
[05/05/2023 12:58:30] WARNING: Could not compress a tex
```

**Comment by IfromTurkey55** [comment]
thank so much my comrade, let me try that

**Comment by IfromTurkey55** [comment]
help kevin

**Comment by IfromTurkey55** [comment]
> 

yes ı am sure?

**Comment by IfromTurkey55** [comment]
> Your new crash report doesn't appear to contain any enabled mod with the name/ID "Hungry Europans" in its list of mods. Are you sure you enabled it?

:(

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/85ab9c10e3582abf14c825ac3ce575c7a9f50a94 by making the game show a warning message when trying to enable a mod that requires some other mods that aren't currently enabled.

**Comment by Rokvach** [comment]
Is it possible to make the workshop ID more human readable i.e. showing the actual name of the mod? Another option would be to turn the ID into a link which links to the mod in workshop. 

steamcommunity.com/sharedfiles/filedetails/?id=

![Image](https://github.com/user-attachments/assets/70ae355a-406d-411d-995c-10f2f9cb464c)

**Comment by IfromTurkey55** [comment]
Thanks 31 Oca 2025 10:31 tarihinde Roni Kovaniemi ***@***.***> yazdı:
Is it possible to make the workshop ID more human readable i.e. showing the actual name of the mod? Another option would be to turn the ID into a link which links to the mod in workshop.
steamcommunity.com/sharedfiles/filedetails/?id=
image.png (view on web)

**Comment by Regalis11** [comment]
The fix has now been merged to our private repo, coming up in the next unstable build and the next update.
