### ISSUE TITLE
crash when trying attach items trough setentityproperties

### ISSUE THREAD

**Issue by Fachoj** [FakeFishGames/Barotrauma#13018]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

game crashes when i used thees command on oxygenite: setentityproperties attachable true, setentityproperties attached true and then tryin to test it. no crash report tho

### Reproduction steps

1 subeditor
2 make any correct sub
3 spawn any non attachable item and select it
4 console commands: setentityproperties attachable true, setentityproperties attached true
5 launch sub

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.1.0 (Unstable)

### -

1.2.1.0 and below

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
game dont produce any crashreport on crash
but there error message on autosave
Coroutine SubEditorAutoSave threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.ItemComponent.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 1047
   at Barotrauma.Items.Components.Holdable.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\Holdable.cs:line 1067
   at Barotrauma.Item.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3989
   at Barotrauma.Submarine.SaveToXElement(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1835
   at Barotrauma.SubEditorScreen.AutoSave() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1656
   at Barotrauma.SubEditorScreen.AutoSaveCoroutine()+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1531
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2af92e3ef98d636b9d4623f3c2b86d3705ec8b32 (commit in our private repo)

**Comment by Fachoj** [comment]
Crashreport with same conditions:

```
Barotrauma Client crash report (generated on 12/19/2023 14:46:22)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

554F9D29F7FAA1A7810FCC7D26552F4B

Game version 1.2.6.0 (ReleaseWindows, branch master, revision a846ff2ea5)
Graphics mode: 1280x1024 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (E6EE74B)
Level seed: no level loaded
Loaded submarine: Dugong (5F91D5FE775A62FD7A2C23B47F5C189C)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTS 450
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1.25}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Xml.Linq.XElement Save(System.Xml.Linq.XElement)
Stack trace: 
   at Barotrauma.Items.Components.ItemComponent.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 1059
   at Barotrauma.Items.Components.Holdable.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\Holdable.cs:line 1067
   at Barotrauma.Item.Save(XElement parentElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 4042
   at Barotrauma.Submarine.SaveToXElement(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1861
   at Barotrauma.SubmarineInfo..ctor(Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 291
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1059
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1252
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 888
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[12/19/2023 14:46:18] Changed the value "Attached" from False to true on item "Oxygenite Shard (ID: 881)", component "Throwable".
[12/19/2023 14:46:18] setentityproperties Attached true
[12/19/2023 14:46:10] Changed the value "Attachable" from False to true on item "Oxygenite Shard (ID: 881)", component "Throwable".
[12/19/2023 14:46:10] setentityproperties Attachable true
```

**Comment by Rokvach** [comment]
Tested by using the repro steps, didn't encounter any crashes in the PR while I did encounter a crash in the Steam build. Working correctly. Can be merged and closed.
