### ISSUE TITLE
Modded game closes server due to networking errors when encountering any form of sea creature.

### ISSUE THREAD

**Issue by Not8BitPyro** [FakeFishGames/Barotrauma#13059]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I have tested this in singleplayer and it works just fine, but when in multiplayer, the server consistently closes when encountering sea creatures.

### Reproduction steps

1. Download this modpack : https://steamcommunity.com/sharedfiles/filedetails/?id=2930566107
2. Install lua for Barotrauma

3. Start a multiplayer game.
3. Continue through the level until meeting any sea creatures.
4. Watch the server immediately close.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 162
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.ReadUInt16() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 183
   at Barotrauma.Inventory.SharedRead(IReadMessage msg, List1[] receivedItemIds, Boolean& readyToApply) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Inventory.cs:line 1079
   at Barotrauma.Inventory.ClientEventRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 1854
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1435
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>cDisplayClass118_0.<ReadIngameUpdate>b0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2120
   at Barotrauma.Networking.SegmentTableReader1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment]
Ultra late-response: I finally got around to attempting to reproduce this, but could not get it to occur (could be that the mods have been updated since, or that the issue has been fixed since).

We've also implemented some extra logging in the latest unstable build that should make the error message a lot more descriptive: it should now tell which entity (character) caused the exception to be thrown and which mod it's from, which should make diagnosing the issue a lot easier in the future if the issue resurfaces.
