### ISSUE TITLE
adding IsOpen="true" to a door/hatch will throw a error

### ISSUE THREAD

**Issue by ricky122122** [FakeFishGames/Barotrauma#13057]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

wanted to have a door opened already for reasons and it throws a error even with the error the property is still set to true

### Reproduction steps

add IsOpen to a vanilla door in the Door Component
then spawn said door in sub editor

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to set the value of the property "IsOpen" of "Barotrauma.Items.Components.Door" to true {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, String value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\SerializableProperty.cs:line 353

Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.Door.UpdateConvexHulls() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Door.cs:line 79
   at Barotrauma.Items.Components.Door.set_OpenState(Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 208
   at Barotrauma.Items.Components.Door.set_IsOpen(Boolean value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 178
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9be12b982e04e014bf96964e7524821262cf246a (commit in our private repo)
