### ISSUE TITLE
Crash when starting the game via Proton (NoSuitableGraphicsDeviceException, "Failed to create graphics device")

### ISSUE THREAD

**Issue by MaxSMokeSkaarj** [FakeFishGames/Barotrauma#13179]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i start game via Proton in steam i got a that error. And when i use primus or not doesn't matter, it gots always, reboot doesn't work. Naitive mode works, but i need proton/win version of game. i3 3120M, GT635M, 390xx driver

### Reproduction steps

1. Start a game in Steam
2. Observe a error window

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Client crash report (generated on 12/17/2023 00:41:09)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0C0A571EE28A0DF68909A59E1461CB5E

Game version 1.2.6.0 (ReleaseWindows, branch release/winter-update, revision d21d6e262c)
Graphics mode: 0x0 (Windowed)
VSync OFF
Language: 
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    Game not initialized

Exception: Failed to create graphics device! (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void CreateDevice()
Stack trace: 
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 122
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 303
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 228
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

InnerException: The type initializer for 'Microsoft.Xna.Framework.Graphics.GraphicsAdapter' threw an exception.
Target site: Microsoft.Xna.Framework.Graphics.GraphicsAdapter get_DefaultAdapter()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsAdapter.get_DefaultAdapter() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsAdapter.cs:line 49
   at Microsoft.Xna.Framework.GraphicsDeviceManager.PrepareGraphicsDeviceInformation(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 289
   at Microsoft.Xna.Framework.GraphicsDeviceManager.DoPreparingDeviceSettings() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 205
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 113
Last debug messages:
[12/17/2023 00:41:09] Logged in as MaxSMoke | Beware of SMoke! (SteamID STEAM_1:1:498982937)
```

**Comment by Regalis11** [comment]
Thank you for the report!

Based on the error message, it seems that the game fails to find your graphics device. I'm not familiar with Proton, so I'm just guessing here, but I wonder if this could have something to do with how Proton and/your graphics drivers have been configured?

**Comment by MaxSMokeSkaarj** [comment]
of course. In naitive mode barotrauma works correctly, probably problem with proton compatibility
