### ISSUE TITLE
Deleting a local mod during a workshop submission causes a crash with System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by drunken-dwarf** [FakeFishGames/Barotrauma#13283]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Deleting a local mod from SteamLibrary/steamapps/common/Barotrauma/LocalMods/ while submitting an item to the workshop using the in-game tools results in a crash upon completion.

I was updating an already existing submission which had ~400mb so the process was slow enough for me to be able to delete a folder (it is a compilation of dozens of mods with a bunch of bug fixes, I would not create such a monster as a standalone mod).

### Reproduction steps

1. Upload or update mod large enough to be able to do file operations during the process
2. Delete existing local mod from Barotrauma/LocalMods/ folder
3. Wait for completion of the upload process
4. Observe crash to desktop/text editor with crash log

### Bug prevalence

Just once

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Exception: Could not find a part of the path '/home/redacted/Games/SteamLibrary/steamapps/common/Barotrauma/LocalMods/Winterhalter test'. (System.IO.DirectoryNotFoundException)
Target site: IntPtr CreateDirectoryHandle(System.String, Boolean)
Stack trace: 
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Barotrauma.Steam.MutableWorkshopMenu.<AddUnpublishedMods>g__getEditTime|33_1(ContentPackage p) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/WorkshopMenu/Mutable/ItemList.cs:line 215
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Barotrauma.Steam.MutableWorkshopMenu.AddUnpublishedMods(ISet`1 workshopItems) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/WorkshopMenu/Mutable/ItemList.cs:line 243
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass36_0.<PopulateItemList>b__0(Task t) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/WorkshopMenu/Mutable/ItemList.cs:line 473
   at Barotrauma.TaskPool.Update() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/TaskPool.cs:line 78
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 916
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by NilanthAnimosus** [comment]
going to close this. in my eyes even if this is still an issue, its abnormal for a user to go deleting their mod manually in the filesystem before its done uploading, and imo doesn't make sense (if this is an issue or not) to go about trying to fix this, as it wouldn't occur under any normal circumstance to lose the directories mid-upload.

If this issue occurs with a new bug report that has it occur during normal usage (Such as throwing the error after uploading without the user removing files) we can make a ticket then.
