### ISSUE TITLE
 Game crashes 20-30 minutes after entering the game.

### ISSUE THREAD

**Issue by KadimSovalye** [FakeFishGames/Barotrauma#13315]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After entering the game, it crashes randomly after 20-30 minutes while trying to complete the missions. Whether I am in a submarine or in a city does not change the crash.

Mods:
-Lua for barotrauma
-Neurotrauma
-BetterHealthUI
-Performance Fix
-Real Sonar
-Barocraftables+
-Backpacks
-32x stacks

### Reproduction steps

-Starting game (save)
-Playing 30-20 minutes
-Randomly Crashing

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable version.

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/16/2024 17:48:51)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F7BF3E1FA262E8BB8787B7DF1F75FC11

Game version 1.2.8.0 (ReleaseWindows, branch master, revision 40beade15a)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: Turkish
Selected content packages: Vanilla (F748F32), Lua For Barotrauma (833D5B9), Neurotrauma (18BA412), BetterHealthUI (5C86226), Performance Fix (E5AC66F), Real Sonar (F501225), BaroCraftables+ (717036B), Backpacks (6D10E98), 32x Stack (911963F)
Level seed: LocationName.city.4940
Loaded submarine: Berilia (D0EE68667485BA2B16AF79FC34131A4B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 654
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/16/2024 17:32:29] Generating an outpost for the start of the level... (Location: Tara şehri, level type: Outpost)
[01/16/2024 17:32:29] Level identifier: outpostlevel
[01/16/2024 17:32:26] ‖color:#9370DB‖[Backpacks]‖color:end‖ WARNING: Potentially invalid damage modifier in "Deep Diving Operation Suit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[01/16/2024 17:27:35] 
/// Running Neurotrauma V A1.8.7 ///
------------------------------------------
- Not running any expansions

[01/16/2024 17:27:23] Generating an outpost for the start of the level... (Location: Tara şehri, level type: Outpost)
[01/16/2024 17:27:23] Level identifier: outpostlevel
[01/16/2024 17:27:18] ‖color:#9370DB‖[Backpacks]‖color:end‖ WARNING: Potentially invalid damage modifier in "Deep Diving Operation Suit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[01/16/2024 17:27:13]  - init.lua (Took 0.00414ms)
[01/16/2024 17:27:13] Performance Fix 1.0.14
[01/16/2024 17:27:13]  - init.lua (Took 0.14371ms)
[01/16/2024 17:27:13] Real Sonar 2.0.2
[01/16/2024 17:27:13]  - init.lua (Took 0.00015ms)
[01/16/2024 17:27:13] Performance Fix 1.0.14
[01/16/2024 17:27:13]  - init.lua (Took 0.05893ms)
[01/16/2024 17:27:13] Neurotrauma A1.8.7
[01/16/2024 17:27:12] Using LuaSetup.lua from the content package.
[01/16/2024 17:27:12] [Client] LuaCsSetup: Completed assembly loading. Total time 2724ms.
[01/16/2024 17:27:12] BetterHealthUIMod..ctor
[01/16/2024 17:27:12] [Client] Loading type: BetterHealthUIMod
[01/16/2024 17:27:11] [Client] Assemblies from CPackage BetterHealthUI loaded with Guid dabe5115-4777-4f92-9401-51036456f368.
[01/16/2024 17:27:09] [Client] Loading scripts for CPackage BetterHealthUI
[01/16/2024 17:27:09] Cs! Version 40beade15a
[01/16/2024 17:27:09] Lua! Version 40beade15a
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'acidburn' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[01/16/2024 17:26:49] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/efeeg/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
```

**Comment by Regalis11** [comment]
Thank you for the report! It seems that this could potentially be caused by mods, since there's nothing on that line in the vanilla code that could be crashing the game, and you seem to be using mods that edit the source code. The error message seems to imply that some item was deleted when items were being updated, which should normally never happen (the deletions shouldn't be processed until the items have been updated).

If I had to guess, I would maybe suspect performance fix, because it does all kinds of weirds things with the code that are known to cause problems.

In any case, I added some debug logging to that part of the code to hopefully help us gather some more info on the issue (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/85398c55768ab6117d47d41e6be3debeb96cfcce). Sorry for the inconvenience! :/

**Comment by Cryorm** [comment]
@Regalis11 Hey boss, It's not performance fix that causes that issue. It's the Neurotrauma mod that's causing it. I had both mods, had the same exact exception being thrown, and I figured it out last night. I already submitted a bug report for the NT team. You're good, ain't your fault!

**Comment by Regalis11** [comment]
@Cryorm That's good to know, thanks! In any case, that extra debug logging should make it easier to diagnose these sorts of crashes in the future, regardless if they're caused by a bug in the vanilla game or a mod. Now the error message will mention which item was being updated/deleted at the same time, which should make it much easier to pinpoint the problem.
