### ISSUE TITLE
[Unstable]: Moving Medical Monitor crashes the game in sub editor

### ISSUE THREAD

**Issue by meatball133** [FakeFishGames/Barotrauma#13382]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was building my awsome looking sub in the sub editor, while working on building the medical compartment I placed a medical monitor. Then I tried moving it and the program just suddenly crash, every time even with nothing else placed.

### Reproduction steps

1. Open the sub editor.
2. Place a medical monitor
3. Click on it.
4. Crash.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

Other

### -

1.2.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/03/2024 10:45:31)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

653B4C0C339A2918D88A91733DA811CC

Game version 1.2.11.0 (UnstableWindows, branch release/spring-update, revision 254572905a)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (7E66F5E), Skearmar (5745596)
Level seed: no level loaded
Loaded submarine: Skearmar (0A059C3466B12AF7C665638EC889C924)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22631.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: String cannot be of zero length. (Parameter 'oldValue') (System.ArgumentException)
Target site: System.String Replace(System.String, System.String)
Stack trace: 
   at System.String.Replace(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue, StringComparison comparisonType)
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass30_0.<CreateStringField>g__StripPrefabTags|7(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 841
   at Barotrauma.SerializableEntityEditor.CreateStringField(ISerializableEntity entity, SerializableProperty property, String value, LocalizedString displayName, LocalizedString toolTip) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 713
   at Barotrauma.SerializableEntityEditor.CreateNewField(SerializableProperty property, ISerializableEntity entity) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 395
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass19_0.<.ctor>b__0(SerializableProperty ep) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 321
   at Barotrauma.Extensions.IEnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 128
   at Barotrauma.SerializableEntityEditor..ctor(RectTransform parent, ISerializableEntity entity, IEnumerable`1 properties, Boolean showName, String style, Int32 elementHeight, GUIFont titleFont) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 321
   at Barotrauma.SerializableEntityEditor..ctor(RectTransform parent, ISerializableEntity entity, Boolean inGame, Boolean showName, String style, Int32 elementHeight, GUIFont titleFont) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 295
   at Barotrauma.Item.CreateEditingHUD(Boolean inGame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 845
   at Barotrauma.Item.UpdateEditing(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 764
   at Barotrauma.MapEntity.UpdateEditor(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 936
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5822
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/03/2024 10:44:29] Attempting to open ALC device "OpenAL Soft on KG251Q (NVIDIA High Definition Audio)"
[02/03/2024 10:44:20] Logged in as Meatball13 (SteamID STEAM_1:1:170169300)
```

**Comment by meatball133** [comment]
Likely an extension to the: https://github.com/FakeFishGames/Barotrauma/issues/13378

**Comment by meatball133** [comment]
X-ray screens are also affected

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/FakeFishGames/Barotrauma/issues/13378, closing as a duplicate
