### ISSUE TITLE
Bug found on guardian hook cannon

### ISSUE THREAD

**Issue by Sr256** [FakeFishGames/Barotrauma#13396]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I wanted to add a tag called 'f' on guardian hook cannon, but when I finnished typing, the game crashed.
I also found that guardian hook cannon will disappear immidiately when I drop it.(I don't know if it can be called a bug) And it didn't lead to crash.

### Reproduction steps

1. Open the editor.
2. Choose any submarine.
3. Enter the 'debugdraw' mode.
4. Place a guardian hook cannon(another guardian weapon can also appear this bug).
5. Typing something into the line of 'tags'.
Another bug
1. Open the editor.
2. Choose any submarine.
3. Enter the 'debugdraw' mode.
4. Place a guardian hook cannon.
5. Enter the testing mode.
Or
1.Put a guardian hook cannon in a container on a submarine.
2.Start a campaign with the submarine including a guardian hook cannon.
3. Get the guardian hook cannon in the inventory and drop it.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub editor

### Version

Other

### -

1.2.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/05/2024 01:10:19)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

653B4C0C339A2918D88A91733DA811CC

Game version 1.2.11.0 (UnstableWindows, branch release/spring-update, revision 254572905a)
Graphics mode: 1620x1080 (Fullscreen)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla (7E66F5E), 三联脉冲激光物资箱 (8C63B5E), 刚素弹药箱 (7873EC6), 冲锋枪弹匣 (B4F90B2), 刚素破片弹药箱 (DFD1946), 刚素连射炮弹药箱 (71A7986), 霰弹破片弹药箱 (BD3A711), 集束破片弹药箱 (4E106DC), 铀燃料棒 (6D3D4D3), 钍燃料棒 (9B367F3), 重机枪弹夹 (EAA28C8), 连射炮弹药箱 (707D71D), 贫化燃料电磁枪弹药箱 (7DC0340), 脉冲激光物资箱 (E88422A), 肥料 (7F834CE), 粉碎者连射炮弹药箱 (0EB7ADE), 突击步枪弹夹 (58DD580), 穿甲弹药箱 (D0E4F19), 电磁线圈 (9E9783F), 电磁枪弹药箱 (5EA1B24), 电池 (56AB930), 爆破弹药箱 (A09BAB6), 焊接油箱 (E1612E2), 烟丝 (188427B), 灭火器架 (2A88EF7), 灭火器 (7618EA0), 液氧罐 (2906356), 氧气罐 (0CE0711), 异星电池 (20C6173), 雷素电池 (F17A9D1), 雷素燃料棒 (A41B582), 超级手电筒 (21A06E6), 超人套装 (AD3A8F6), 胜利誓约 (3F378A0), 泰然自若 (0448F7C), 应急预案 (4823EEF), 运货小车 (1C192E1), 常规排水阀门 (5EFBFF1), 禁闭室大门 (C65A325), 燃料棒套餐 (AB9C9B4), 自动防卫系统 (F5BF016), 高爆破片弹药箱 (E8BB7A9), 波塞冬之矛 (5BF6110), 真理 (9F21334), 应援棒 (B1735A2), 弹药架 (353FD14), 垂直通道门 (0AA7EF2), 排水装置 (D7F4F76), 乌托邦 (F016204), 物质凝聚器 (6CE1CB3), 小型排水阀门 (D049318), 小型垂直通道门 (C0194B9), 电池阵列控制器 (B4D98D3), 淹没反应 (E79BE9D), 医药柜 (2A9FA3C), 快捷修复方式 (D91F057), 守护者武库 (76E6FF8), 对接口 (B0F95AE), 水平隔离门 (4ED8434)
Level seed: no level loaded
Loaded submarine: 旧日级 (A63910EDBBED2CBBE68B167535ABCCFA)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: Intel(R) Iris(R) Plus Graphics
    Display mode: {Width:1620 Height:1080 Format:Color AspectRatio:1.5}
    GPU status: Normal

Exception: String cannot be of zero length. (Parameter 'oldValue') (System.ArgumentException)
Target site: System.String Replace(System.String, System.String)
Stack trace: 
   at System.String.Replace(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue, StringComparison comparisonType)
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass30_0.<CreateStringField>g__StripPrefabTags|7(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 846
   at Barotrauma.SerializableEntityEditor.CreateStringField(ISerializableEntity entity, SerializableProperty property, String value, LocalizedString displayName, LocalizedString toolTip) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 0
   at Barotrauma.SerializableEntityEditor.CreateNewField(SerializableProperty property, ISerializableEntity entity) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 395
   at Barotrauma.SerializableEntityEditor.<>c__DisplayClass19_0.<.ctor>b__0(SerializableProperty ep) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 321
   at Barotrauma.Extensions.IEnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 128
   at Barotrauma.SerializableEntityEditor..ctor(RectTransform parent, ISerializableEntity entity, IEnumerable`1 properties, Boolean showName, String style, Int32 elementHeight, GUIFont titleFont) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Serialization\SerializableEntityEditor.cs:line 325
   at Barotrauma.Item.CreateEditingHUD(Boolean inGame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 845
   at Barotrauma.Item.UpdateEditing(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 764
   at Barotrauma.MapEntity.UpdateEditor(Camera cam, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 936
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5822
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/05/2024 01:07:43] Debug draw mode disabled
[02/05/2024 01:07:43] debugdraw
[02/05/2024 01:07:30] Debug draw mode enabled
[02/05/2024 01:07:30] debugdraw
[02/05/2024 01:05:42] Generating an outpost for the start of the level... (Location: 阿提斯前哨站, level type: Outpost)
[02/05/2024 01:05:42] Level identifier: outpostlevel
[02/05/2024 01:04:22] Generating an outpost for the start of the level... (Location: 科加沃斯托克前哨站, level type: Outpost)
[02/05/2024 01:04:22] Level identifier: outpostlevel
[02/05/2024 01:02:32] Generating an outpost for the start of the level... (Location: 托姆斯代尔航路前哨站, level type: Outpost)
[02/05/2024 01:02:32] Level identifier: outpostlevel
[02/05/2024 01:00:56] Generating an outpost for the start of the level... (Location: 利比亚航路居住前哨站, level type: Outpost)
[02/05/2024 01:00:56] Level identifier: outpostlevel
[02/05/2024 00:54:48] Generating an outpost for the start of the level... (Location: 科加沃斯托克居住前哨站, level type: Outpost)
[02/05/2024 00:54:48] Level identifier: outpostlevel
[02/05/2024 00:54:25] Debug draw mode enabled
[02/05/2024 00:54:25] debugdraw
[02/05/2024 00:51:53] Debug draw mode enabled
[02/05/2024 00:51:53] debugdraw
[02/05/2024 00:37:23] Generating an outpost for the start of the level... (Location: 戴菲尔德前哨站, level type: Outpost)
[02/05/2024 00:37:23] Level identifier: outpostlevel
[02/05/2024 00:34:57] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek High Definition Audio(SST))"
[02/05/2024 00:34:55] Logged in as Sr256 (SteamID STEAM_1:0:597145201)
```

**Comment by Regalis11** [comment]
Seems to be the same crash as https://github.com/FakeFishGames/Barotrauma/issues/13378, closing as a duplicate
