### ISSUE TITLE
Failed to spawn item

### ISSUE THREAD

**Issue by Virtlink** [FakeFishGames/Barotrauma#13452]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

We ended a three-player multiplayer scenario, and while loading the outpost, the game crashed on my client only with the following exception:

```
Failed to spawn item Pomegrenade {ID 10705 is taken by Pomegrenade (ID: 10705)}
```

I was not hosting this game, and the person hosting this game already finished loading.

### Reproduction steps

We encountered this bug after many many hours of playing. It might not be easily reproducible. We had a plant farm that spawned pomegranades. I suspect it's a race condition.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Failed to spawn item Pomegrenade {ID 10705 is taken by Pomegrenade (ID: 10705)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 273
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1031
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1024
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1935

Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: ID 10705 is taken by Pomegrenade (ID: 10705)
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 273
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1031
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1024
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1935
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 13
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>c__DisplayClass118_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2121
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment]
Thank you for the report!

I suspect this could be the same issue as https://github.com/FakeFishGames/Barotrauma/issues/12699: I've seen these sorts of "ID taken by x" errors occur when a new round starts before a client finishes loading a previous one. Hard to say for sure though - do you by any chance know or remember if two rounds were started in very rapid succession like this when the issue occurred?

**Comment by Virtlink** [comment]
No, no rounds were started in rapid succession. This happened on a three-player multiplayer game on the transition from a scenario (that we played for 10 minutes or more) to an outpost. The host had already loaded into the outpost, and one other player finished loading a minute later. My client was still loading, and felt like it could be done any second, when the exception happened.
