### ISSUE TITLE
Game keeps crashing seemingly at random

### ISSUE THREAD

**Issue by ieatshoes** [FakeFishGames/Barotrauma#13450]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Game crashes in the middle of seemingly any mission type

### Reproduction steps

Dont know what specifically causes this, the crashes happen at random

[Save 1.zip](https://github.com/FakeFishGames/Barotrauma/files/14324466/Save.1.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/18/2024 15:03:07)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F7BF3E1FA262E8BB8787B7DF1F75FC11

Game version 1.2.8.0 (ReleaseWindows, branch master, revision 40beade15a)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla (F748F32), Enhanced Armaments (1E1F0B9), Enhanced Armaments Neurotrauma Patch (A5754DA), Neurotrauma (18BA412), NT Cybernetics (67B8763), NT Symbiote (00A18D7), More Level Content (09241C4), Breaking Bad Guitar (794CD21), Beacons Extended (E83E173), SFB with DE (6D87557), CsForBarotrauma (09E517F), Scannable wild plants (Lua) 扫描野外植物 (01D9939), 32x Stack (911963F), BetterHealthUI (5C86226), Rysky 2 (BF1DAFF), R-278 «Dugong» (FB6E838), Stations from beyond (6D95E69), Lua For Barotrauma (833D5B9), DynamicEuropa - Default Level Size Patch (3E67028), Enhanced Armaments DynamicEuropa Patch (9E76BF2), Shipwrecks Extended (F0A7A9B), DynamicEuropa (49FB9E7)
Level seed: Anid141
Loaded submarine: R-278 «Dugong» [ENG] (A26607031BAC6BD089DFF1EC4299DA34)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 654
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/18/2024 14:58:44] Wild plants are now scannable
[02/18/2024 14:58:43] [CLIENT] No subs in autofill queue
[02/18/2024 14:58:43] [CLIENT] Auto filling subs
[02/18/2024 14:58:36] [CLIENT] Decorating Caves
[02/18/2024 14:58:31] Generating an outpost for the start of the level... (Location: Anid, level type: Outpost)
[02/18/2024 14:58:31] Level identifier: ridgeoutpost
[02/18/2024 14:58:18] [CLIENT] Level has no distress mission
[02/18/2024 14:58:18] 
/// Running Neurotrauma V A1.8.7 ///
------------------------------------------
+ Cybernetics V A1.2.4h1
+ Symbiote V A1.0.0h1

[02/18/2024 14:58:17] [CLIENT] Map has construction sites
[02/18/2024 14:58:17] [CLIENT] OnMapLoad:Postfix
[02/18/2024 14:58:16]  - patch.lua (Took 0.03879ms)
[02/18/2024 14:58:16] Dont Open Debug Console On Errors 1.0.5
[02/18/2024 14:58:16]  - init.lua (Took 0.06576ms)
[02/18/2024 14:58:16] Performance Fix 1.0.14
[02/18/2024 14:58:16]  - ScannablePlant.lua (Took 0.00513ms)
[02/18/2024 14:58:16] Scannable wild plants (Lua) 扫描野外植物 1.0.0
[02/18/2024 14:58:16]  - init.lua (Took 0.00511ms)
[02/18/2024 14:58:16] NT Symbiote A1.0.0h1
[02/18/2024 14:58:16]  - init.lua (Took 0.00580ms)
[02/18/2024 14:58:16] NT Cybernetics A1.2.4h1
[02/18/2024 14:58:16]  - init.lua (Took 0.21083ms)
[02/18/2024 14:58:15] Neurotrauma A1.8.7
[02/18/2024 14:58:13] Using LuaSetup.lua from the content package.
[02/18/2024 14:58:13] [Client] LuaCsSetup: Completed assembly loading. Total time 12562ms.
[02/18/2024 14:58:13] BetterHealthUIMod..ctor
[02/18/2024 14:58:13] [CLIENT] -= MLC Compatability =-
- HazReactor: False
- Neurotrauma: True
[02/18/2024 14:58:13] [CLIENT] Patched Hooks
[02/18/2024 14:58:13] [CLIENT] Injecting custom missions
[02/18/2024 14:58:13] [CLIENT] Collected 163 other files to check
[02/18/2024 14:58:11] [CLIENT] Collected 11 pirate outposts
[02/18/2024 14:58:11] [CLIENT] Sorting modules by their diff ranges...
[02/18/2024 14:58:08] [CLIENT] Collecting pirate outposts...
[02/18/2024 14:58:08] [CLIENT] Saved config to disk!
[02/18/2024 14:58:08] [CLIENT] Saved config to disk!
[02/18/2024 14:58:08] [CLIENT] [CLIENT] Config Updated
[02/18/2024 14:58:07] [CLIENT] Mod Init
[02/18/2024 14:58:07] [Client] Loading type: BetterHealthUIMod
[02/18/2024 14:58:07] [Client] Loading type: Main
[02/18/2024 14:58:07] [Client] Assemblies from CPackage BetterHealthUI loaded with Guid dac25375-efb5-47f1-a51b-935129e9cf69.
[02/18/2024 14:58:06] [Client] Loading scripts for CPackage BetterHealthUI
[02/18/2024 14:58:06] [Client] Assemblies from CPackage More Level Content loaded with Guid 7eebeed5-431d-46e6-9a9a-4e41ce1843e6.
[02/18/2024 14:58:02] [Client] Loading scripts for CPackage More Level Content
[02/18/2024 14:58:01] Cs! Version 40beade15a
[02/18/2024 14:58:00] Lua! Version 40beade15a
[02/18/2024 14:57:07] ‖color:#9370DB‖[DynamicEuropa]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/UI/DE-IconsAtlas.png, size: 1365x1365)
[02/18/2024 14:56:38] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3068776800/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'acidburn' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:37] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/justi/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[02/18/2024 14:56:20] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[02/18/2024 14:56:18] Logged in as Ieatsocks69 (SteamID STEAM_1:1:123152872)
```

**Comment by evilfactory** [comment]
Looking at the crash report it looks like it's caused by neurotrauma, since that mod currently has a bug which throws the collection was modified exception at random during the round.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/FakeFishGames/Barotrauma/issues/13315 (and seems to be an issue in a mod we unfortunately can't address ourselves).

@evilfactory Have you considered making Lua for Barotrauma handle this exception? Or maybe do something like enumerating a copy of the entity list so modifying it "on the fly" doesn't crash the game?

**Comment by evilfactory** [comment]
I could change the original MapEntity UpdateAll so it doesn't crash the game, but this is ultimately an issue with the mod incorrectly spawning/removing items without making use of EntitySpawner.
