### ISSUE TITLE
Failed to spawn item

### ISSUE THREAD

**Issue by ArvineRone** [FakeFishGames/Barotrauma#13497]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The issue is similar to #13452 but occurs on different conditions. 
The issue occurs during multiplayer mid-round, when playing on dedicated server or server started via in-game menu, even if i am the only player on the server.
The issue causes the server to crash.

### Reproduction steps

The issue occurs when a new item appears to spawn for example, by deconstructing an item or firing a coilgun.
The two conflicting items can be modded or vanilla items, in any combination. 
The issue occurs regularly.
The issue persisted after playing with same mod list, on different PC.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to spawn item Water Electrifier {ID 6843 is taken by Metal Crate (ID: 6843)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 277
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1032
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1025
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1935

Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: ID 6843 is taken by Metal Crate (ID: 6843)
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 277
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1032
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1025
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1935
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 13
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>c__DisplayClass118_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2123
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment]
Thank you for the report! Based on the crash log, this seems to be the same bug as https://github.com/FakeFishGames/Barotrauma/issues/13452 (even though it might be triggering in a slightly different scenario in this case).
