### ISSUE TITLE
ArtifactEvent crashes the game if that item does not exist

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13577]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

when ArtifactEvent tries to spawn a non-existing item, the game crashes
in my opinion, the game should skip this spawn instead of crashing the game

### Reproduction steps

1. create an ArtifactEvent spawning something that does not exist
2. unlock and start a new round
3. the game instantly crashed the moment level has been generated

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void .ctor(Barotrauma.ItemPrefab, Microsoft.Xna.Framework.Vector2, Barotrauma.Submarine, UInt16, Boolean)
Stack trace: 
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1025
   at Barotrauma.ArtifactEvent.SpawnItem() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ArtifactEvent.cs:line 81
   at Barotrauma.ArtifactEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ArtifactEvent.cs:line 111
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 892
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 796
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 143
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/18/2024 21:22:32] ‖color:#9370DB‖[Custom EventSet]‖color:end‖ Error in ArtifactEvent - couldn't find an item prefab with the identifier rust1artifact
[03/18/2024 21:22:32] ‖color:#9370DB‖[Custom EventSet]‖color:end‖ Error in ArtifactEvent - couldn't find an item prefab with the identifier rust2artifact
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/e7de0479ff8f5913930d920cd563d26fe4418170

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5070/commits/52bf3d320703b6329832cf99af5e94b3f6bc7c10

Created an event that spawn artifacts, it gave no errors.
`<ArtifactEvent identifier="testartifact" itemidentifier="skyholderartifact" />`

Malformed the itemidentifier to `noartifact` and got error without crash
`Error in ArtifactEvent - couldn't find an item prefab with the identifier notartifact`

No issues found, closing ticket as resolved.
