### ISSUE TITLE
[Unstable] Beacon stations crashing server on activating

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13745]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13731

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** April  5, 2024</sup>
### What happened?

Activating a beacon sometimes causes the server to crash
Observed on several different beacons

https://github.com/FakeFishGames/Barotrauma/assets/37850646/f67522ee-450f-4ccd-9c43-9927120afb56

### Reproduction steps

1. host a server, select mission mode and select beacon mission
2. power up the beacon
3. activate the beacon
4. observe that sometimes the server crashes and you are sent to the main menu

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.1.0 (unstable)

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 04/06/2024 04:58:22)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 1.4.1.0 (UnstableWindows, branch release/spring-update, revision ed3db81c2c)
Language: English
Selected content packages: Vanilla (B895671)
Level seed: gorbeUlc
Loaded submarine: Azimuth (A46F8A0DDBE9374BB0678F1C97C74A79)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateMissionSpecific(Single)
Stack trace: 
   at Barotrauma.BeaconMission.UpdateMissionSpecific(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\BeaconMission.cs:line 140
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 836
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 147
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 332
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 85


Last debug messages:
   04/06/2024 04:58:22 - [04/06/2024 04:58:22]
  Saving banlist
   04/06/2024 04:58:22 - [04/06/2024 04:58:22]
  Mission info:  - The beacon station is back online. Make sure it stays transmitting, and navigate the submarine to Skadi's Cauldron Mine to claim your reward.
   04/06/2024 04:58:19 - [04/06/2024 04:58:19]
  Vyk equipped Fuel Rod
   04/06/2024 04:58:18 - [04/06/2024 04:58:18]
  Console command "teleportcharacter" executed by Vyk.
   04/06/2024 04:58:16 - [04/06/2024 04:58:16]
  Vyk adjusted reactor settings: Temperature: 15, Fission rate: 1, Turbine output: 0, Autotemp ON
   04/06/2024 04:58:15 - [04/06/2024 04:58:15]
  Vyk adjusted reactor settings: Temperature: 0, Fission rate: 0, Turbine output: 0, Autotemp OFF
   04/06/2024 04:58:14 - [04/06/2024 04:58:14]
  Vyk placed Fuel Rod in Nuclear Reactor (ID: 4864)
   04/06/2024 04:58:12 - [04/06/2024 04:58:12]
  Console command "teleportcharacter" executed by Vyk.
   04/06/2024 04:58:12 - [04/06/2024 04:58:12]
  Console command "fixhulls" executed by Vyk.
   04/06/2024 04:58:10 - [04/06/2024 04:58:10]
  Console command "fixitems" executed by Vyk.
   04/06/2024 04:58:08 - [04/06/2024 04:58:08]
  Console command "teleportcharacter" executed by Vyk.
   04/06/2024 04:58:07 - [04/06/2024 04:58:07]
  Console command "teleportcharacter" executed by Vyk.
   04/06/2024 04:58:06 - [04/06/2024 04:58:06]
  Console command "teleportcharacter" executed by Vyk.
   04/06/2024 04:58:06 - [04/06/2024 04:58:06]
  Console command "teleportcharacter" executed by Vyk.
```
</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5138, fix coming up in the next unstable build
