### ISSUE TITLE
Thalamus fleshspike causes a crash in multiplayer

### ISSUE THREAD

**Issue by Jasontti** [FakeFishGames/Barotrauma#13907]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13906

<div type='discussions-op-text'>

<sup>Originally posted by **Jasontti** April 30, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When fleshspike from thalamus wreck fires, it causes server to crash.
MP save file for testing:
[thalamus-fleshspike-crash-MP-save.zip](https://github.com/FakeFishGames/Barotrauma/files/15160184/thalamus-fleshspike-crash-MP-save.zip)

### Reproduction steps

1. Start multiplayer sandbox game or use included save file
2. Look for thalamussed wreck with fleshspike
3. Get in the range of the fleshspike

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.5.0 (Blood in the Water Update, hotfix 1)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Process terminated. Assertion failed.                                                                                                                                
Tried to create Turret EventData with no projectile.
   at Barotrauma.Items.Components.Turret.EventData..ctor(Item projectile, Turret turret) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 891
   at Barotrauma.Items.Components.Turret.Launch(Item projectile, Character user, Nullable`1 launchRotation, Single tinkeringStrength) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 980
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 847
   at Barotrauma.Items.Components.Turret.UpdateAutoOperate(Single deltaTime, Boolean ignorePower, Identifier friendlyTag) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 1209
   at Barotrauma.SubmarineTurretAI.OperateTurrets(Single deltaTime, Identifier friendlyTag) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Wreck/WreckAI.cs:line 83
   at Barotrauma.WreckAI.Update(Single deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Wreck/WreckAI.cs:line 326
   at Barotrauma.Submarine.Update(Single deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1162
   at Barotrauma.GameScreen.Update(Double deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 273
   at Barotrauma.GameMain.Run() in /dev/Barotrauma-development/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in /dev/Barotrauma-development/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 85
```
</div>

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5268/commits/6cc0dcfe8ed332b9d7fa82adfc479c6c0932d73c

Tested in SP and MP
Tested all thalamus and player turret types

No issues found
Closing ticket
