### ISSUE TITLE
Bug Report: When starting a new game, the game just crashes with an error

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13940]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13935

<div type='discussions-op-text'>

<sup>Originally posted by **Eboblo** May  7, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When starting a new game, the game just crashes with an error
An error appears with the text:
Oops! Barotrauma just crashed.
A crash report ("crash report (2).log") was saved in the root
folder of the game. The error was not sent to the developers
because user statistics have been disabled, but if you'd
like to help fix this bug, you may post it on Barotraumas
GitHub issue tracker:
https://github.com/Regalis11/Barotrauma/issues/
--------------------------------------------------
Сrash report text: 
Barotrauma Client crash report (generated on 05/07/2024 12:19:39)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

8002F5C26E4B79C3640F9AD2B2BBA4B9

Game version 1.4.6.0 (ReleaseWindows, branch release/spring-update-hotfix-2, revision 3513066f44)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (329B29B)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Access to the path 'C:\Users\Данила\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub' is denied. (System.UnauthorizedAccessException)
Target site: Void CopyFile(System.String, System.String, Boolean)
Stack trace: 
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Barotrauma.IO.File.Copy(String src, String dest, Boolean overwrite) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 350
   at Barotrauma.MainMenuScreen.StartGame(SubmarineInfo selectedSub, String savePath, String mapSeed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen\MainMenuScreen.cs:line 1280
   at Barotrauma.SinglePlayerCampaignSetupUI.FinishSetup(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 458
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1262
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 967
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[05/07/2024 12:18:51] Attempting to open ALC device "OpenAL Soft on Headphones (High Definition Audio Device)"
[05/07/2024 12:18:48] Logged in as Анальная астма (SteamID STEAM_1:0:119283861)

### Reproduction steps

1. Started the game. 2. Set up the world for solo passage. 3. Clicked "Start the game"

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment]
Fixed in the next unstable.
