### ISSUE TITLE
Game keeps crashing after docking to the station.

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14080]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14078

<div type='discussions-op-text'>

<sup>Originally posted by **Twice4** June  2, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I dont want to remove the station mod, because I will have to start the campaign from ground up. Please let me know what I can do

Here is the bug report 
Barotrauma Client crash report (generated on 06/02/2024 16:09:45)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

E3BBD9786909CCFB62D3AFBC61FF783D

Game version 1.4.6.0 (ReleaseWindows, branch lua-xpath-1.4.6, revision 9e83fa9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (329B29B), Lua For Barotrauma (with xpath patch) (D79CA4B), Lua For Barotrauma (BBB172E), Lua Linker (A3ECE31), CsForBarotrauma (09E517F), Performance Fix (E5AC66F), EuropaWaifu++ (04F6169), EuropaWaifu++ EK mods Patch (A8867BE), Real Sonar (28D9B77), Soundproof Walls (935F334), DynamicEuropa (4BBFAA2), More Level Content (D29FCDB), EK Mods for 1.x.x.x (1C26ECD), Complete Global Darkness (91A9E43), Shiftless (A348C06), Meaningful Upgrades (76AC2CE), wellerman (6A0734C), Sardine (8A52E40), Movable and Sellable Wrecks (ADFB499), Shipwrecks Extended (F0A7A9B), Wreck Locator (CFABD6F), New Wrecks For Barotrauma (With sellable wrecks) (D956E6C), Beacons Extended (E83E173), Dont Open Debug Console On Errors (59B0D91), Super Plague Rat (70A0B4E), PlagueRat (D9ECAFA), Cast Iron (23F4AC3), Super Plague Rat 1.0.9 my ver (B652C11), Super Plague Rat SONAR 1.0.9 m (6ACC419), The Plague Rat 2.9.4 new (AE58ED5), Ammoshelf (AB91C3B)
Level seed: Eightercua Fossa80
Loaded submarine: The Plague Rat 2.9.4 Tier 1 (AB327A6DFB418CF99A5D1EB7193F07BF)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2080 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.RagdollParams get_Ragdoll()
Stack trace: 
   at Barotrauma.CharacterInfo.get_Ragdoll() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 568
   at Barotrauma.HumanoidAnimController.get_HumanRagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 43
   at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 467
   at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/AnimController.cs:line 225
   at Barotrauma.HumanoidAnimController..ctor(Character character, String seed, HumanRagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 208
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1506
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1326
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1296
   at Barotrauma.EntitySpawner.CharacterSpawnInfo.Spawn() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs:line 152
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs:line 438
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 608
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 950
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 61

Last debug messages:
[06/02/2024 16:09:32] [CLIENT] No subs in autofill queue
[06/02/2024 16:09:32] [CLIENT] Auto filling subs
[06/02/2024 16:09:32] Potential error in StatusEffect (Compact SMG, RangedWeapon). Target not defined, the effect might not work correctly. Use target="This" if you want the effect to target the entity it's defined in. Setting "This" as the target.
[06/02/2024 16:09:32] Potential error in StatusEffect (Compact SMG, RangedWeapon). Target not defined, the effect might not work correctly. Use target="This" if you want the effect to target the entity it's defined in. Setting "This" as the target.
[06/02/2024 16:09:28] [CLIENT] Decorating Caves
[06/02/2024 16:09:25] ‖color:#9370DB‖[EuropaWaifu++]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/Items/Posters.png, size: 655x851)
[06/02/2024 16:09:25] ‖color:#9370DB‖[Real Sonar]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2936760984/Icons/divingsuitcontainerwindow.png, size: 77x214)
[06/02/2024 16:09:23] Generating an outpost for the start of the level... (Location: Eightercua Fossa Industry, level type: Outpost)
[06/02/2024 16:09:23] Loading additional background creatures from file 'C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/BackgroundCreatures/BackgroundCreaturePrefabs.xml'
[06/02/2024 16:09:23] Level identifier: coldcavernsoutpost
[06/02/2024 16:09:18] ‖color:#9370DB‖[Real Sonar]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2936760984/Icons/medicines.png, size: 148x69)
[06/02/2024 16:09:15] [CLIENT] Level has no distress mission
[06/02/2024 16:09:15] [CLIENT] Map has construction sites
[06/02/2024 16:09:15] [CLIENT] OnMapLoad:Postfix
[06/02/2024 16:09:14]  - patch.lua (Took 0.02716ms)
[06/02/2024 16:09:14] Dont Open Debug Console On Errors 1.0.5
[06/02/2024 16:09:14]  - init.lua (Took 0.00611ms)
[06/02/2024 16:09:14] Performance Fix 1.0.14
[06/02/2024 16:09:14]  - sellablewrecks.lua (Took 0.00101ms)
[06/02/2024 16:09:14]  - movablewrecks.lua (Took 0.00286ms)
[06/02/2024 16:09:14] Movable and Sellable Wrecks 1.5
[06/02/2024 16:09:14]  - NoItemHighlight.lua (Took 0.00019ms)
[06/02/2024 16:09:14]  - LevelDarkness.lua (Took 0.00018ms)
[06/02/2024 16:09:14]  - HullDarkness.lua (Took 0.00020ms)
[06/02/2024 16:09:14] Complete Global Darkness 1.0.3
[06/02/2024 16:09:14]  - init.lua (Took 0.17421ms)
[06/02/2024 16:09:14] Real Sonar 2.0.3
[06/02/2024 16:09:14]  - init.lua (Took 0.00018ms)
[06/02/2024 16:09:14] Performance Fix 1.0.14
[06/02/2024 16:09:14]  - lualinker.lua (Took 0.00095ms)
[06/02/2024 16:09:14]  - luaDisplaySideBySide.lua (Took 0.00317ms)
[06/02/2024 16:09:14] Lua Linker 1.2.1
[06/02/2024 16:09:12] Using LuaSetup.lua from the content package.
[06/02/2024 16:09:12] [Client] LuaCsSetup: Completed assembly loading. Total time 19446ms.
[06/02/2024 16:09:12] [CLIENT] -= MLC Compatability =-
- HazReactor: False
- Neurotrauma: False
[06/02/2024 16:09:12] [CLIENT] Patched Hooks
[06/02/2024 16:09:12] [CLIENT] Injecting custom missions
[06/02/2024 16:09:12] WARNING: Using FromPackage on xpath. Will not evaluate path changes in inheritance!
[06/02/2024 16:09:12] WARNING: Using FromPackage on xpath. Will not evaluate path changes in inheritance!
[06/02/2024 16:09:12] [CLIENT] Collected 3 other files to check
[06/02/2024 16:09:11] [CLIENT] Collected 11 pirate outposts
[06/02/2024 16:09:11] [CLIENT] Sorting modules by their diff ranges...
[06/02/2024 16:09:10] [CLIENT] Collecting pirate outposts...
[06/02/2024 16:09:10] [CLIENT] Saved config to disk!
[06/02/2024 16:09:10] [CLIENT] Saved config to disk!
[06/02/2024 16:09:10] [CLIENT] [CLIENT] Config Updated
[06/02/2024 16:09:09] [CLIENT] Mod Init
[06/02/2024 16:09:09] [Client] Loading type: SoundproofWalls
[06/02/2024 16:09:09] [Client] Loading type: Main
[06/02/2024 16:09:09] [Client] Assemblies from CPackage Soundproof Walls loaded with Guid 31d1f859-f6f9-491d-9c0d-4dc17ae81f20.
[06/02/2024 16:09:09] [Client] Loading assemblies for CPackage Soundproof Walls
[06/02/2024 16:09:09] [Client] Assemblies from CPackage More Level Content loaded with Guid de166adc-04c7-4e60-9bde-3686773c840d.
[06/02/2024 16:09:07] [Client] Loading scripts for CPackage More Level Content
[06/02/2024 16:08:53] Cs! Version 9e83fa9
[06/02/2024 16:08:53] Lua! Version 9e83fa9
[06/02/2024 16:08:40] Container tag "wrecksecurearmcab" is used in vanilla item prefabs but not defined in a ContainerTagPrefab.
[06/02/2024 16:08:40] Container tag "wreckshuttlecrate" is used in vanilla item prefabs but not defined in a ContainerTagPrefab.
[06/02/2024 16:08:20] ‖color:#9370DB‖[EuropaWaifu++]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/UI/titleText.png, size: 1161x1024)
[06/02/2024 16:08:14] ‖color:#9370DB‖[Meaningful Upgrades]‖color:end‖ WARNING: Upgrade "increasecomponenthealth" is affecting a property that is also being affected by "decreasedeteriorationspeed".
This is unsupported and might yield unexpected results if both upgrades are applied at the same time to the same item.
Add the attribute suppresswarnings="true" to your XML element to disable this warning if you know what you're doing.
[06/02/2024 16:07:56] Attempting to open ALC device "OpenAL Soft on Наушники (Samson Stereo)"
[06/02/2024 16:07:54] Logged in as Twice (SteamID STEAM_1:1:87262339)

### Reproduction steps

1. Began single player campaign with mods. 2. Docked to the station. 3. Game crushes upon loading the station

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/02/2024 16:09:45)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

E3BBD9786909CCFB62D3AFBC61FF783D

Game version 1.4.6.0 (ReleaseWindows, branch lua-xpath-1.4.6, revision 9e83fa9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (329B29B), Lua For Barotrauma (with xpath patch) (D79CA4B), Lua For Barotrauma (BBB172E), Lua Linker (A3ECE31), CsForBarotrauma (09E517F), Performance Fix (E5AC66F), EuropaWaifu++ (04F6169), EuropaWaifu++ EK mods Patch (A8867BE), Real Sonar (28D9B77), Soundproof Walls (935F334), DynamicEuropa (4BBFAA2), More Level Content (D29FCDB), EK Mods for 1.x.x.x (1C26ECD), Complete Global Darkness (91A9E43), Shiftless (A348C06), Meaningful Upgrades (76AC2CE), wellerman (6A0734C), Sardine (8A52E40), Movable and Sellable Wrecks (ADFB499), Shipwrecks Extended (F0A7A9B), Wreck Locator (CFABD6F), New Wrecks For Barotrauma (With sellable wrecks) (D956E6C), Beacons Extended (E83E173), Dont Open Debug Console On Errors (59B0D91), Super Plague Rat (70A0B4E), PlagueRat (D9ECAFA), Cast Iron (23F4AC3), Super Plague Rat 1.0.9 my ver (B652C11), Super Plague Rat SONAR 1.0.9 m (6ACC419), The Plague Rat 2.9.4 new (AE58ED5), Ammoshelf (AB91C3B)
Level seed: Eightercua Fossa80
Loaded submarine: The Plague Rat 2.9.4 Tier 1 (AB327A6DFB418CF99A5D1EB7193F07BF)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2080 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.RagdollParams get_Ragdoll()
Stack trace: 
   at Barotrauma.CharacterInfo.get_Ragdoll() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 568
   at Barotrauma.HumanoidAnimController.get_HumanRagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 43
   at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 467
   at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/AnimController.cs:line 225
   at Barotrauma.HumanoidAnimController..ctor(Character character, String seed, HumanRagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 208
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1506
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1326
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1296
   at Barotrauma.EntitySpawner.CharacterSpawnInfo.Spawn() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs:line 152
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs:line 438
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 608
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 950
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Markus\RiderProjects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 61

Last debug messages:
[06/02/2024 16:09:32] [CLIENT] No subs in autofill queue
[06/02/2024 16:09:32] [CLIENT] Auto filling subs
[06/02/2024 16:09:32] Potential error in StatusEffect (Compact SMG, RangedWeapon). Target not defined, the effect might not work correctly. Use target="This" if you want the effect to target the entity it's defined in. Setting "This" as the target.
[06/02/2024 16:09:32] Potential error in StatusEffect (Compact SMG, RangedWeapon). Target not defined, the effect might not work correctly. Use target="This" if you want the effect to target the entity it's defined in. Setting "This" as the target.
[06/02/2024 16:09:28] [CLIENT] Decorating Caves
[06/02/2024 16:09:25] ‖color:#9370DB‖[EuropaWaifu++]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/Items/Posters.png, size: 655x851)
[06/02/2024 16:09:25] ‖color:#9370DB‖[Real Sonar]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2936760984/Icons/divingsuitcontainerwindow.png, size: 77x214)
[06/02/2024 16:09:23] Generating an outpost for the start of the level... (Location: Eightercua Fossa Industry, level type: Outpost)
[06/02/2024 16:09:23] Loading additional background creatures from file 'C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2532991202/BackgroundCreatures/BackgroundCreaturePrefabs.xml'
[06/02/2024 16:09:23] Level identifier: coldcavernsoutpost
[06/02/2024 16:09:18] ‖color:#9370DB‖[Real Sonar]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2936760984/Icons/medicines.png, size: 148x69)
[06/02/2024 16:09:15] [CLIENT] Level has no distress mission
[06/02/2024 16:09:15] [CLIENT] Map has construction sites
[06/02/2024 16:09:15] [CLIENT] OnMapLoad:Postfix
[06/02/2024 16:09:14]  - patch.lua (Took 0.02716ms)
[06/02/2024 16:09:14] Dont Open Debug Console On Errors 1.0.5
[06/02/2024 16:09:14]  - init.lua (Took 0.00611ms)
[06/02/2024 16:09:14] Performance Fix 1.0.14
[06/02/2024 16:09:14]  - sellablewrecks.lua (Took 0.00101ms)
[06/02/2024 16:09:14]  - movablewrecks.lua (Took 0.00286ms)
[06/02/2024 16:09:14] Movable and Sellable Wrecks 1.5
[06/02/2024 16:09:14]  - NoItemHighlight.lua (Took 0.00019ms)
[06/02/2024 16:09:14]  - LevelDarkness.lua (Took 0.00018ms)
[06/02/2024 16:09:14]  - HullDarkness.lua (Took 0.00020ms)
[06/02/2024 16:09:14] Complete Global Darkness 1.0.3
[06/02/2024 16:09:14]  - init.lua (Took 0.17421ms)
[06/02/2024 16:09:14] Real Sonar 2.0.3
[06/02/2024 16:09:14]  - init.lua (Took 0.00018ms)
[06/02/2024 16:09:14] Performance Fix 1.0.14
[06/02/2024 16:09:14]  - lualinker.lua (Took 0.00095ms)
[06/02/2024 16:09:14]  - luaDisplaySideBySide.lua (Took 0.00317ms)
[06/02/2024 16:09:14] Lua Linker 1.2.1
[06/02/2024 16:09:12] Using LuaSetup.lua from the content package.
[06/02/2024 16:09:12] [Client] LuaCsSetup: Completed assembly loading. Total time 19446ms.
[06/02/2024 16:09:12] [CLIENT] -= MLC Compatability =-
- HazReactor: False
- Neurotrauma: False
[06/02/2024 16:09:12] [CLIENT] Patched Hooks
[06/02/2024 16:09:12] [CLIENT] Injecting custom missions
[06/02/2024 16:09:12] WARNING: Using FromPackage on xpath. Will not evaluate path changes in inheritance!
[06/02/2024 16:09:12] WARNING: Using FromPackage on xpath. Will not evaluate path changes in inheritance!
[06/02/2024 16:09:12] [CLIENT] Collected 3 other files to check
[06/02/2024 16:09:11] [CLIENT] Collected 11 pirate outposts
[06/02/2024 16:09:11] [CLIENT] Sorting modules by their diff ranges...
[06/02/2024 16:09:10] [CLIENT] Collecting pirate outposts...
[06/02/2024 16:09:10] [CLIENT] Saved config to disk!
[06/02/2024 16:09:10] [CLIENT] Saved config to disk!
[06/02/2024 16:09:10] [CLIENT] [CLIENT] Config Updated
[06/02/2024 16:09:09] [CLIENT] Mod Init
[06/02/2024 16:09:09] [Client] Loading type: SoundproofWalls
[06/02/2024 16:09:09] [Client] Loading type: Main
[06/02/2024 16:09:09] [Client] Assemblies from CPackage Soundproof Walls loaded with Guid 31d1f859-f6f9-491d-9c0d-4dc17ae81f20.
[06/02/2024 16:09:09] [Client] Loading assemblies for CPackage Soundproof Walls
[06/02/2024 16:09:09] [Client] Assemblies from CPackage More Level Content loaded with Guid de166adc-04c7-4e60-9bde-3686773c840d.
[06/02/2024 16:09:07] [Client] Loading scripts for CPackage More Level Content
[06/02/2024 16:08:53] Cs! Version 9e83fa9
[06/02/2024 16:08:53] Lua! Version 9e83fa9
[06/02/2024 16:08:40] Container tag "wrecksecurearmcab" is used in vanilla item prefabs but not defined in a ContainerTagPrefab.
[06/02/2024 16:08:40] Container tag "wreckshuttlecrate" is used in vanilla item prefabs but not defined in a ContainerTagPrefab.
[06/02/2024 16:08:20] ‖color:#9370DB‖[EuropaWaifu++]‖color:end‖ WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Boom Ratte/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2648774153/UI/titleText.png, size: 1161x1024)
[06/02/2024 16:08:14] ‖color:#9370DB‖[Meaningful Upgrades]‖color:end‖ WARNING: Upgrade "increasecomponenthealth" is affecting a property that is also being affected by "decreasedeteriorationspeed".
This is unsupported and might yield unexpected results if both upgrades are applied at the same time to the same item.
Add the attribute suppresswarnings="true" to your XML element to disable this warning if you know what you're doing.
[06/02/2024 16:07:56] Attempting to open ALC device "OpenAL Soft on Наушники (Samson Stereo)"
[06/02/2024 16:07:54] Logged in as Twice (SteamID STEAM_1:1:87262339)
```
</div>

**Comment by itchyOwl** [comment]
Moved to QA investigates, because reproducing the crash would require installing all the mods. The stack trace is slighthly off and it's not easy to see what's actually crashing (or why). But most likely there's an issue with some mod adding/modifying characters. Would at least have to make the crash more descipritive, or prevent crashing, if possible.

Also requested that the reporter would try to narrow it down by turning mods off one by one and seeing which one is the one crashing the game.
