### ISSUE TITLE
Crash when left an outpost that bots are deconstructing (AIObjectiveDeconstructItems.IsValidTarget)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14353]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14220

<div type='discussions-op-text'>

<sup>Originally posted by **kaedepon** June 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game version is `v1.5.8.0` in this report.

I assign deconstruction to 2 bots.
And I left an outpost while the bots were working.
This message was displayed and the game was crashed.
`The items the bots left inside the outpost have been automatically moved to the submarine.`

### Reproduction steps

1. Assign deconstruction to 2 bots.
2. Left an outpost.
3. Crashed the game.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### -

v1.5.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/27/2024 20:51:07)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F044EF888C05A3F21D2D4CFED0919DC7

Game version 1.5.8.0 (ReleaseWindows, branch release/summer-update-hotfix, revision eb8d06ccea)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Japanese
Selected content packages: Vanilla (C0006C7)
Level seed: LocationName.city.4816LocationName.generic.2157
Loaded submarine: Orca2 (68F4757C57F243C0197946B2D8C412E8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 4060 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsValidTarget(Barotrauma.Item)
Stack trace: 
   at Barotrauma.AIObjectiveDeconstructItems.IsValidTarget(Item target) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveDeconstructItems.cs:line 64
   at Barotrauma.AIObjectiveLoop`1.FindTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 203
   at Barotrauma.AIObjectiveLoop`1.UpdateTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 189
   at Barotrauma.AIObjectiveLoop`1.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 97
   at Barotrauma.AIObjectiveManager.UpdateObjectives(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 289
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 394
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3305
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[06/27/2024 20:50:58] Generating an outpost for the end of the level... (Location: Beenalaght Fossa研究センター, level type: LocationConnection)
[06/27/2024 20:50:56] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: LocationConnection)
[06/27/2024 20:50:53] Level identifier: ridgebasic
[06/27/2024 20:50:30] Transitioning to LocationName.city.4816LocationName.generic.2157 (current location: St. Musk研究所, selected location: Beenalaght Fossa研究センター, leaving sub: Orca2, at start: True, at end: False, transition type: LeaveLocation)
[06/27/2024 20:50:22] Unlocked mission "トリフィル石の採掘" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:45:15] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: Outpost)
[06/27/2024 20:45:15] Level identifier: ridgeoutpost
[06/27/2024 20:44:21] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: Outpost)
[06/27/2024 20:44:21] Level identifier: ridgeoutpost
[06/27/2024 20:38:41] Unlocked mission "信者の輸送" in the connection from "St. Musk研究所" to "Molovsk施設".
[06/27/2024 20:38:21] Unlocked mission "武器の配送" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:38:19] Unlocked mission "スレッシャーの群れを始末" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:38:16] Unlocked mission "貨物回収" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:38:15] Unlocked mission "連合軍要人の輸送" in the connection from "St. Musk研究所" to "Beenalaght Fossa研究センター".
[06/27/2024 20:37:50] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: Outpost)
[06/27/2024 20:37:50] Level identifier: ridgeoutpost
[06/27/2024 20:37:38] Unlocked mission "武器の配送" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:37:36] Unlocked mission "スレッシャーの群れを始末" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:37:34] Unlocked mission "貨物回収" in the connection from "St. Musk研究所" to "Molovsk施設".
[06/27/2024 20:37:32] Unlocked mission "連合軍要人の輸送" in the connection from "St. Musk研究所" to "Molovsk施設".
[06/27/2024 20:37:08] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: Outpost)
[06/27/2024 20:37:08] Level identifier: ridgeoutpost
[06/27/2024 20:36:51] Unlocked mission "武器の配送" in the connection from "St. Musk研究所" to "Beenalaght Fossa研究センター".
[06/27/2024 20:36:49] Unlocked mission "スレッシャーの群れを始末" in the connection from "St. Musk研究所" to "Molovsk施設".
[06/27/2024 20:36:47] Unlocked mission "貨物回収" in the connection from "St. Musk研究所" to "Molovsk施設".
[06/27/2024 20:36:45] Unlocked mission "連合軍要人の輸送" in the connection from "St. Musk研究所" to "Gope居住基地".
[06/27/2024 20:36:10] Generating an outpost for the start of the level... (Location: St. Musk研究所, level type: Outpost)
[06/27/2024 20:36:10] Level identifier: ridgeoutpost
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:57] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:56] Result "UnexpectedError" was not handled by "UnlockAchievements".
[06/27/2024 20:35:56] Transitioning to LocationName.city.4816 (current location: Tormsdale Linea基地, selected location: St. Musk研究所, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[06/27/2024 20:32:44] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: LocationConnection)
[06/27/2024 20:32:42] Generating an outpost for the end of the level... (Location: St. Musk研究所, level type: LocationConnection)
[06/27/2024 20:32:41] Level identifier: ridgebasic
[06/27/2024 20:32:27] Transitioning to LocationName.city.4816LocationName.generic.9544 (current location: Tormsdale Linea基地, selected location: St. Musk研究所, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[06/27/2024 20:26:05] Unlocked mission "武器の配送" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:26:03] Unlocked mission "緑鉛鉱の採掘" in the connection from "Tormsdale Linea基地" to "Adonis Linea鉱床".
[06/27/2024 20:26:01] Unlocked mission "取扱注意" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:25:59] Unlocked mission "難破船回収" in the connection from "Tormsdale Linea基地" to "Novaya Moskva要塞".
[06/27/2024 20:25:59] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: No suitable mission matching the level difficulty 15 found with the tag "salvagewreck". Ignoring the restriction.
[06/27/2024 20:25:56] Unlocked mission "ラングバイン石の採掘" in the connection from "Tormsdale Linea基地" to "Novaya Moskva要塞".
[06/27/2024 20:25:54] Unlocked mission "囚人護送" in the connection from "Tormsdale Linea基地" to "Gope居住基地".
[06/27/2024 20:25:53] Unlocked mission "連合軍人員の輸送" in the connection from "Tormsdale Linea基地" to "Set研究センター".
[06/27/2024 20:25:30] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:25:30] Level identifier: ridgeoutpost
[06/27/2024 20:25:17] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:25:17] Level identifier: ridgeoutpost
[06/27/2024 20:24:23] Unlocked mission "武器の配送" in the connection from "Tormsdale Linea基地" to "Adonis Linea鉱床".
[06/27/2024 20:24:21] Unlocked mission "緑鉛鉱の採掘" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:24:19] Unlocked mission "取扱注意" in the connection from "Tormsdale Linea基地" to "Gope居住基地".
[06/27/2024 20:24:16] Unlocked mission "難破船回収" in the connection from "Tormsdale Linea基地" to "Novaya Moskva要塞".
[06/27/2024 20:24:16] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: No suitable mission matching the level difficulty 15 found with the tag "salvagewreck". Ignoring the restriction.
[06/27/2024 20:24:14] Unlocked mission "ラングバイン石の採掘" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:24:12] Unlocked mission "囚人護送" in the connection from "Tormsdale Linea基地" to "Set研究センター".
[06/27/2024 20:24:11] Unlocked mission "連合軍人員の輸送" in the connection from "Tormsdale Linea基地" to "Set研究センター".
[06/27/2024 20:23:48] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:23:48] Level identifier: ridgeoutpost
[06/27/2024 20:23:37] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:23:37] Level identifier: ridgeoutpost
[06/27/2024 20:22:11] Unlocked mission "武器の配送" in the connection from "Tormsdale Linea基地" to "Adonis Linea鉱床".
[06/27/2024 20:22:09] Unlocked mission "緑鉛鉱の採掘" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:22:07] Unlocked mission "取扱注意" in the connection from "Tormsdale Linea基地" to "Set研究センター".
[06/27/2024 20:22:05] Unlocked mission "難破船回収" in the connection from "Tormsdale Linea基地" to "St. Musk研究所".
[06/27/2024 20:22:05] ‖color:#9370DB‖[Vanilla]‖color:end‖ WARNING: No suitable mission matching the level difficulty 15 found with the tag "salvagewreck". Ignoring the restriction.
[06/27/2024 20:22:03] Unlocked mission "ラングバイン石の採掘" in the connection from "Tormsdale Linea基地" to "Gope居住基地".
[06/27/2024 20:22:01] Unlocked mission "囚人護送" in the connection from "Tormsdale Linea基地" to "Novaya Moskva要塞".
[06/27/2024 20:21:59] Unlocked mission "連合軍人員の輸送" in the connection from "Tormsdale Linea基地" to "Set研究センター".
[06/27/2024 20:21:35] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:21:35] Level identifier: ridgeoutpost
[06/27/2024 20:21:16] Generating an outpost for the start of the level... (Location: Tormsdale Linea基地, level type: Outpost)
[06/27/2024 20:21:16] Level identifier: ridgeoutpost
[06/27/2024 20:18:10] Attempting to open ALC device "OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)"
[06/27/2024 20:18:07] Logged in as kaede (SteamID STEAM_1:1:79963658)
```
</div>

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the crash either but hopefully the null checks catches the crash. Can be merged and closed.
