### ISSUE TITLE
Some red warning when deleting all wires in sub editor (circuit box error, wire is not in an inventory)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14711]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14709

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** September 24, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Happens on save / autosave after deleting all wires with Ctrl+A
Apparently wires from Circut boxes
Mb they just shouldn't be selected with Ctrl+A

Idk how important is this

### Reproduction steps

1. Open any sub in editor
2. In "Toggle visibility" menu choose only wires
3. Ctrl + A
4. delete
5. F3 / Ctrl + S

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

On autosave
```CoffeeScript
Coroutine SubEditorAutoSave threw an exception: Item "Blue Wire" is not in an inventory.
   at Barotrauma.ItemSlotIndexPair.Serialize(Item item) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/ItemSlotIndexPair.cs:line 23
   at Barotrauma.CircuitBoxWire.Save() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxWire.cs:line 46
   at Barotrauma.Items.Components.CircuitBox.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 275
   at Barotrauma.Item.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 4186
   at Barotrauma.Submarine.SaveToXElement(XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1993
   at Barotrauma.SubEditorScreen.AutoSave() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1682
   at Barotrauma.SubEditorScreen.AutoSaveCoroutine()+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1557
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 236
```

On Ctrl + S

```shell
An error occurred while trying to save Barsuk123 {Item "Blue Wire" is not in an inventory.}
   at Barotrauma.ItemSlotIndexPair.Serialize(Item item) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/ItemSlotIndexPair.cs:line 23
   at Barotrauma.CircuitBoxWire.Save() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxWire.cs:line 46
   at Barotrauma.Items.Components.CircuitBox.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 275
   at Barotrauma.Item.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 4186
   at Barotrauma.Submarine.SaveToXElement(XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1993
   at Barotrauma.SubmarineInfo..ctor(Submarine sub) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/SubmarineInfo.cs:line 296
   at Barotrauma.Submarine.TrySaveAs(String filePath, MemoryStream previewImage) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 2001
   at Barotrauma.SubEditorScreen.<>c__DisplayClass128_0.<SaveSubToFile>g__addSubAndSave|1(ModProject modProject, String filePath, String packagePath) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 2004
   at Barotrauma.SubEditorScreen.SaveSubToFile(String name, ContentPackage packageToSaveTo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1964
   at Barotrauma.SubEditorScreen.<>c__DisplayClass125_0.<SaveSub>b__1() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1822
   at Barotrauma.SubEditorScreen.<>c__DisplayClass125_0.<SaveSub>g__handleExceptions|0(Action action) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1779
Coroutine SubEditorAutoSave threw an exception: Item "Blue Wire" is not in an inventory.
   at Barotrauma.ItemSlotIndexPair.Serialize(Item item) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/ItemSlotIndexPair.cs:line 23
   at Barotrauma.CircuitBoxWire.Save() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxWire.cs:line 46
   at Barotrauma.Items.Components.CircuitBox.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 275
   at Barotrauma.Item.Save(XElement parentElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 4186
   at Barotrauma.Submarine.SaveToXElement(XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1993
   at Barotrauma.SubEditorScreen.AutoSave() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1682
   at Barotrauma.SubEditorScreen.AutoSaveCoroutine()+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1557
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 236
```</div>

**Comment by Regalis11** [comment]
Merged, closing
