### ISSUE TITLE
[Unstable] Cannot start outpost deathmatch

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14786]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14775

<div type='discussions-op-text'>

<sup>Originally posted by **Efflorescized** October  6, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to start an outpost deathmatch game put all of us back to the lobby screen, not being able to play the mode. Additionally, one of the players had their team constantly switched between coalition and separatist without player input, although we didn't try to investigate it further.

https://github.com/user-attachments/assets/9d3cb0a3-b945-4117-b2b2-f25c9a54e8dc

### Reproduction steps

1. Start a multiplayer lobby
2. Select the outpost deathmatch mission type exclusively
3. Have enough players all/most sided on one team, outbalancing the other
4. Start the outpost deathmatch

Doing these steps should accurately reproduce the problem I've faced in the attachment above.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

1.6.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__119 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 674
   at Barotrauma.GameSession.StartRound(String levelSeed, Nullable`1 difficulty, LevelGenerationParams levelGenerationParams, Identifier forceBiome) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 514
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1554
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
```
</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/23f00a509d86c7f7719665ab0677794c81f69218

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5832#issuecomment-2398958501
No issues found
