### ISSUE TITLE
[Unstable] Error while updating item 'Alien Power Cell'

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14818]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14813

<div type='discussions-op-text'>

<sup>Originally posted by **Ek-Videogames** October 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crash a few seconds after the start of the round, ruin initialization? Happened during a 'cear alien ruin' mission.

### Reproduction steps

Happened during a 'clearing a ruin' mission in multiplayer campaign.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.4.0 (unstable)

### -

v1.6.15.0 (pre-steam public release?)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Error while updating item Alien Power Cell (System.InvalidOperationException)
Target site: Void UpdateAll(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 662
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61
```
</div>

**Comment by Regalis11** [comment]
No known steps to repro and didn't get any further info in the discussions, closing
