### ISSUE TITLE
Exception when checking mechanic talents GUI.

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14880]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14874

<div type='discussions-op-text'>

<sup>Originally posted by **OverwatchVoice** October 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a wild one.
The game crashes under very specific circumstances that seem to revolve around the **number of** **owned defense robots** the mechanic has **changing in a round**, and then proceeding to check the **talent tree GUI of the mechanic** that built it.

Aditionally, entering certain types of wrecks at any point by any crewmember in the round, and then opening the talent tree of a mechanic with at least one defense robot to their name also causes a crash. (Only specific structures seem to trigger this, I am not sure if the wreck type is what makes this one work, or if some specific item inside the wreck causes this.)

In either of the above scenarios, opening the talents GUI before the outlined conditions does not seem to have any effect.
I couldn't replicate either scenario outside of the singleplayer.

In either scenario, the crash log is the same.

### Reproduction steps

1. Start a singleplayer campaign.
2. As a mechanic with the "Robotics" talent unlocked, construct a defense robot.
3. In the same round, open the talent tree GUI again.
4. Game go kaputt

The conditions for the wreck-related crash are unbeknownst to me, and I've only been able to pull it off consistently in "wreck1" of
[my own singleplayer campaign.](https://cdn.discordapp.com/attachments/668819422919524352/1297731019050586143/Colds_below.save?ex=6716fdb1&is=6715ac31&hm=a1f8e7727710739bfdc2d501156f348c68b70fe6b22430a32be77b487bfe31fe&)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.6.17.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
`Game version 1.6.17.0 (ReleaseWindows, branch release/autumn-update, revision aa6050b27f)
Graphics mode: 3440x1440 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla (3758FF2)
Level seed: LocationName.generic.6840LocationName.generic.2866
Loaded submarine: Orca (C9BE29D4BD29CE4745B9596AF97D4511)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060
    Display mode: {Width:3440 Height:1440 Format:Color AspectRatio:2.3888888}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsTalentLocked(Barotrauma.Identifier, System.Collections.Generic.IEnumerable`1[Barotrauma.Character])
Stack trace: 
   at Barotrauma.TalentTree.IsTalentLocked(Identifier talentIdentifier, IEnumerable`1 characterList) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\TalentTree.cs:line 168
   at Barotrauma.TalentTree.IsViableTalentForCharacter(Character character, Identifier talentIdentifier, IReadOnlyCollection`1 selectedTalents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\TalentTree.cs:line 130
   at Barotrauma.TalentTree.CheckTalentSelection(Character controlledCharacter, IEnumerable`1 selectedTalents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\TalentTree.cs:line 186
   at Barotrauma.TalentMenu.UpdateTalentInfo() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TalentMenu.cs:line 868
   at Barotrauma.TalentMenu.CreateGUI(GUIFrame parent, Character targetCharacter) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TalentMenu.cs:line 126
   at Barotrauma.TabMenu.SelectInfoFrameTab(InfoFrameTab selectedTab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 464
   at Barotrauma.TabMenu..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 174
   at Barotrauma.GameSession.ToggleTabMenu() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 41
   at Barotrauma.GameSession.UpdateProjSpecific(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 273
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 144
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61`
```
</div>

**Comment by itchyOwl** [comment]
Based on the stack trace, can't reason about on how could we get an exception there, so would have to try to repro it.

**Comment by NilanthAnimosus** [comment]
closed as merged.
