### ISSUE TITLE
Crash in mod overriding Human.xml with wrong ragdolls folder

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14990]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14987

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** October 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

So, i tried to make a mod that overrides human.xml, i set wrong path for ragdolls folder
Game let me enable it
Then i opened sub editor and mod crashed in the console with "Console Error.log"
And then i pressed esc and game crashed with "crashreportslim.log"

Mb it's just this specific mod, mb it's any mod that crash at runtime, i couldn't craft simpler crashing mod

### Reproduction steps

1. enable [this](https://steamcommunity.com/sharedfiles/filedetails/?id=3356379133) 
2. go to sub editor
3. press esc

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.18.1 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

Console Error.log
```CoffeeScript
‖color:#9370DB‖[Error]‖color:end‖ [RagdollParams] Invalid directory: Content/Characters/Human/Bugdolls. Using the default ragdoll.
Couldn`t load xml document "Content/Characters/Human/Bugdolls/HumanDefaultRagdoll.xml"! {Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Content\Characters\Human\Bugdolls\HumanDefaultRagdoll.xml'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share, Boolean catchUnauthorizedAccessExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 540
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 112
‖color:#9370DB‖[Error]‖color:end‖ [EditableParams] The document is null! Failed to load the parameters.
Coroutine Barotrauma.MainMenuScreen+<SelectScreenWithWaitCursor>d__48 threw an exception: [RagdollParams] Failed to load ragdoll Human Default Ragdoll from Content/Characters/Human/Bugdolls\HumanDefaultRagdoll.xml for the character human.
   at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, Identifier ragdollSpecies, Either`2 file, ContentPackage contentPackage) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 298
   at Barotrauma.RagdollParams.GetDefaultRagdollParams[T](Identifier speciesName, XElement characterRootElement, ContentPackage contentPackage) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Params\Ragdoll\RagdollParams.cs:line 208
   at Barotrauma.CharacterInfo.get_Ragdoll() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterInfo.cs:line 593
   at Barotrauma.HumanoidAnimController.get_HumanRagdollParams() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 43
   at Barotrauma.HumanoidAnimController.get_RagdollParams() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 26
   at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 465
   at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\AnimController.cs:line 203
   at Barotrauma.HumanoidAnimController..ctor(Character character, String seed, HumanRagdollParams ragdollParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 208
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1556
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1348
   at Barotrauma.SubEditorScreen.CreateDummyCharacter() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1664
   at Barotrauma.SubEditorScreen.Select(Boolean enableAutoSave) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1492
   at Barotrauma.SubEditorScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1373
   at Barotrauma.MainMenuScreen.SelectScreenWithWaitCursor(Screen screen)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen\MainMenuScreen.cs:line 841
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 213
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 223
```
crashreportslim.log
```CoffeeScript
Exception handler failed: One or more errors occurred. (Object reference not set to an instance of an object.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Barotrauma.SubmarineInfo.get_MD5Hash() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 167
   at Barotrauma.Program.CrashDump(GameMain game, String filePath, Exception exception) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 182
   at Barotrauma.Program.CrashHandler(Object sender, UnhandledExceptionEventArgs args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 76

Initial exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.CircuitBox.IsCircuitBoxSelected(Character character) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 833
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5765
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61
```</div>

**Comment by Regalis11** [comment]
Merged, closing
