### ISSUE TITLE
Items with specific fabrication recipes cannot be loaded

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15258]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15234

<div type='discussions-op-text'>

<sup>Originally posted by **4-S-H** November 23, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

```
<?xml version="1.0" encoding="utf-8"?>
<Items>
  <Item identifier="testitem">
    <Fabricate>
      <RequiredItem tag="anysamestring" />
    </Fabricate>
    <Fabricate>
      <RequiredItem identifier="anysamestring" />
    </Fabricate>
  </Item>
</Items>
```
This file cannot be loaded (not because of lacking a sprite). There are occasions where the two recipes do not necessarily mean the same thing (or overlap at all).
Making the two recipes different in many other ways (different requiredtime, different amount, other different items in the recipes, etc.) fixes the problem.
I suspect that it is due to some hash-related function in ItemPrefab.cs not distinguishing between RequiredItemByIdentifier and RequiredItemByTag.

### Reproduction steps

-

### Bug prevalence

Just once

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load "LocalMods/test/items.xml": Object reference not set to an instance of an object.
   at Barotrauma.ItemPrefab.ParseConfigElement(ItemPrefab variantOf) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 1175
   at Barotrauma.ItemPrefab..ctor(ContentXElement element, ItemFile file) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 1001
   at Barotrauma.ItemFile.CreatePrefab(ContentXElement element) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\ItemFile.cs:line 15
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 36
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 53
   at Barotrauma.ContentPackage.<>c__DisplayClass58_0.<<LoadContentEnumerable>g__loadFiles|1>d.MoveNext() in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 283
```
</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/2ed8e5bd3b6235e899d0a9ac8e6b556be03bbb13
