### ISSUE TITLE
Cannot dumpeventtexts

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15340]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14342

<div type='discussions-op-text'>

<sup>Originally posted by **lIllIIlI** July 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Trying to translate some chinese mods to english. i.e Touhou Deep Sea Operation
Instead I get this:
![image](https://github.com/user-attachments/assets/1d6ff809-783b-4edf-8f98-c26d77858b72)

### Reproduction steps

Subscribe to this mod.
https://steamcommunity.com/sharedfiles/filedetails/?id=2941124988&searchtext=touhou
Do dumpeventtexts in debug console
voila. red text

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Main menu

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Cannot write all lines to "Content/Texts/EventTexts.txt": modifying the files in this folder/with this extension is not allowed.Failed to open the file "Content/Texts/EventTexts.txt". {An error occurred trying to start process 'A:\SteamLibrary\steamapps\common\Barotrauma\Content\Texts\EventTexts.txt' with working directory 'A:\SteamLibrary\steamapps\common\Barotrauma'. The system cannot find the file specified.}
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.ToolBox.OpenFileWithShell(String filename) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\ToolBox.cs:line 507
   at Barotrauma.DebugConsole.<>c.<InitProjectSpecific>b__23_99(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 2779
Cannot write XML document to "A:\SteamLibrary\steamapps\common\Barotrauma\Content\TraitorEvents.xml": modifying the files in this folder/with this extension is not allowed.
Cannot write to invalid XmlWriter
Cannot flush invalid XmlWriter
Cannot dispose invalid XmlWriter
```
</div>

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/8aa4ed63a08120f545cfc47de7e5cd46e6083617

**Comment by Jasontti** [comment]
Latest testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6149#issuecomment-2642840716
Closing ticket as completed.
