### ISSUE TITLE
Crash during startup (TrimSpeciallyHandledCategoriesCache)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15403]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15398

<div type='discussions-op-text'>

<sup>Originally posted by **HawkinsThe71st** December 18, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I got this one-time crash while my game was launching, I'm unsure what caused it or how to reproduce it.

### Reproduction steps

Launch game(?)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.7.7.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12/18/2024 15:32:04)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

DE79AB7C97BF1974D6671DDF491EEBF1

Game version 1.7.7.0 (ReleaseWindows, branch release/winter-update, revision 1486ec8c86)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (661D9E5)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22631.0 64 bit
    GPU name: AMD Radeon RX 6650 XT
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Value cannot be null. (Parameter 'key') (System.ArgumentNullException)
Target site: Void ThrowArgumentNullException(System.ExceptionArgument)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUIFont.GetFontForStr(String str) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIPrefab.cs:line 247
   at Barotrauma.LoadingScreen.Draw(SpriteBatch spriteBatch, GraphicsDevice graphics, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\LoadingScreen.cs:line 239
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1080
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.ScalableFont.WrapText(String text, Single width, Int32 requestCharPos, Vector2& requestedCharPos, Boolean returnAllCharPositions, Vector2[]& allCharPositions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 758
   at Barotrauma.WrappedLString.RetrieveValue() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Text\LocalizedString\WrappedLString.cs:line 27
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 314
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 325
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 325
[12/18/2024 15:32:04] Failed to add a message to the debug console. {Value cannot be null. (Parameter 'key')}
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at Barotrauma.TextManager.TrimSpeciallyHandledCategoriesCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 169
   at Barotrauma.TextManager.GetSpeciallyHandledCategories(String text) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Text\TextManager.cs:line 154
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 436
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 357
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.AddMessage(ColoredText msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 325
[12/18/2024 15:32:00] Result "UnexpectedError" was not handled by "UnlockAchievements".
[12/18/2024 15:31:51] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[12/18/2024 15:31:49] Logged in as Hawkins (SteamID STEAM_1:1:72180162)
```
</div>

**Comment by Regalis11** [comment]
Possibly fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/5d2a6836f0180beab562f6766b64d9b65949c1c2

**Comment by Regalis11** [comment]
Merged, closing.
