### ISSUE TITLE
Crash report: Texture is disposed @ SpriteBatch.CheckValid

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [FakeFishGames/Barotrauma#8979]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The game crashed while in the sub editor

**Steps To Reproduce**

(Not sure; couldn't replicate—feel free to close if the stacktrace doesn't suggest anything on your end)

**Version**

v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

**Additional information**

GPU: Radeon HD 7870

OS: Ubuntu MATE 20.04 LTS

```log
﻿Barotrauma Client crash report (generated on 04/26/2022 01:03:20)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1248F5EFE3252F20D21AD0C7AC802ABE


Game version 0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Dog, Foray
Level seed: no level loaded
Loaded submarine: Foray (EB71D40D45CD619FEACD87606C8B5E65)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Unix 5.13.0.40 64 bit
    GPU name: 
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/SpriteBatch.cs:line 472
   at Barotrauma.Sprite.DrawTiled(ISpriteBatch spriteBatch, Vector2 position, Vector2 targetSize, Nullable`1 color, Nullable`1 startOffset, Nullable`1 textureScale, Nullable`1 depth) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sprite/Sprite.cs:line 372
   at Barotrauma.Structure.Draw(SpriteBatch spriteBatch, Boolean editing, Boolean back, Effect damageEffect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Structure.cs:line 347
   at Barotrauma.Submarine.DrawBack(SpriteBatch spriteBatch, Boolean editing, Predicate`1 predicate) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Submarine.cs:line 210
   at Barotrauma.SubEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 5315
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 970
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[04/25/2022 23:25:35] spawnitem "Oxygenite Shard" cursor
[04/25/2022 23:25:28] spawnitem "Oxygenite Shard" cursor
[04/25/2022 23:25:25] Item "oxygenite shardcursor" not found!
[04/25/2022 23:25:25] spawnitem "Oxygenite Shard"cursor
[04/25/2022 23:25:04] Character "inside" not found
[04/25/2022 23:25:04] spawnitem "Oxygenite Shard" inside
[04/25/2022 23:24:54] spawnitem "Oxygenite Tank" inventory
[04/25/2022 23:24:45] spawnitem "Plasma Cutter" inventory
[04/25/2022 23:21:06] spawnitem "Velonaceps Calyx Eggs" inventory
[04/25/2022 23:19:48] air
[04/25/2022 23:19:06] air
[04/25/2022 23:15:00] spawn Crawler_hatchling outside
[04/25/2022 23:15:00] spawn Crawler_hatchling outside
[04/25/2022 23:15:00] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:59] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:58] spawn Crawler_hatchling outside
[04/25/2022 23:14:56] spawn Crawler_hatchling outside
[04/25/2022 23:14:53] spawn Crawler_hatchling outside
[04/25/2022 22:53:49] spawn Crawler_hatchling cursor
[04/25/2022 22:53:46] spawn Crawler_hatchling cursor
[04/25/2022 22:53:38] spawn Crawler_hatchling cursor
[04/25/2022 22:53:20] Water editing on
[04/25/2022 22:53:20] water 
[04/25/2022 22:53:16] air
[04/25/2022 22:52:58] spawn Crawler_hatchling cursor
[04/25/2022 22:52:39] spawnitem "Oxygenite Shard" cursor
[04/25/2022 22:52:25] air
[04/25/2022 22:48:14] spawn Crawler cursor
[04/25/2022 22:47:17] Steam achievements have been disabled during this play session.
[04/25/2022 22:47:17] Enabled cheat commands.
[04/25/2022 22:47:17] enablecheats
[04/25/2022 19:33:09] Command "clear" not found.
[04/25/2022 19:33:09] clear
[04/25/2022 18:07:27] Attempting to open ALC device "Built-in Audio Analog Stereo"
[04/25/2022 18:07:24] Logged in as starboy98 (SteamID STEAM_1:0:64963800)
```

**Comment by DerDu** [comment]
Same here while loading a vanilla sub having some walls placed and a linked sub (yes, i have no idea what i'am doing, just clicking things ^^)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/9459479/crashreport.log)
![image](https://user-images.githubusercontent.com/616953/187619479-08dcf3eb-38c7-4dd8-80ff-b4fab06e3053.png)

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
